import { BG, TEXT, BORDER, FONT, SPACING, SPECTRUM, RESEARCHER, hexToRgba } from "@/src/styles/tokens";
import { SiteHeader, SiteFooter, ResearcherHero } from "@/src/components";
import GlossaryList from "./GlossaryList";

export const metadata = {
  title: "Glossary | TEG-Blue Research",
  description: "Key terms and concepts used throughout TEG-Blue research. Includes definitions for regulatory states, complexity markers, and core framework concepts.",
  alternates: {
    canonical: "https://teg-blue.org/glossary",
  },
};

// Glossary terms from the approved content
const GLOSSARY_TERMS = [
  // ===== F1: THE EMOTIONAL GRADIENT =====
  {
    slug: "emotional-somatic-system",
    title: "Emotional-Somatic System",
    type: "concept",
    status: "proposed",
    definition: "The biological information system that processes safety, threat, needs, and values through whole-body coordination. Emotions are not disruptions to clear thinking — they are data from a guidance system that predates language and cognition.",
    tags: ["F1", "neuroscience", "core-concept"],
    framework: 1,
  },
  {
    slug: "emotional-compass",
    title: "Emotional Compass",
    type: "concept",
    status: "proposed",
    definition: "The nervous system's continuous orientation between safety/connection and threat/protection. This compass is always scanning, asking: 'Is there enough safety to engage, or is protection needed?'",
    tags: ["F1", "neuroscience", "core-concept"],
    framework: 1,
  },
  {
    slug: "emotional-gradient",
    title: "Emotional Gradient",
    type: "concept",
    status: "proposed",
    definition: "The spectrum along which emotional experience shifts based on nervous system state. The same emotion expresses differently depending on position — fear in safety informs without overwhelming; fear in threat triggers fight, flight, or freeze.",
    tags: ["F1", "measurement", "core-concept"],
    framework: 1,
  },
  {
    slug: "pattern-a-safety",
    title: "Pattern A (Safety Orientation)",
    type: "concept",
    status: "proposed",
    definition: "Regulatory state when safety is perceived. Ventral vagal dominant. Enables engagement, learning, curiosity, and care. Characterized by broad perceptual field, full empathy access, cognitive flexibility, and high heart rate variability. This is not 'calm' or 'happy' — it is the state where the nervous system has sufficient safety resources to engage with challenge without defensive collapse.",
    tags: ["F1", "polyvagal", "regulatory-state"],
    framework: 1,
  },
  {
    slug: "pattern-b-threat",
    title: "Pattern B (Threat Response)",
    type: "concept",
    status: "proposed",
    definition: "Regulatory state when threat is perceived. Sympathetic or dorsal vagal dominant. Enables defense, boundary-setting, and survival responses. Characterized by narrow perceptual field, reduced empathy access, cognitive rigidity, and reduced heart rate variability. This is not dysfunction — it is accurate adaptation to perceived danger.",
    tags: ["F1", "polyvagal", "regulatory-state"],
    framework: 1,
  },
  {
    slug: "four-mode-gradient",
    title: "Four-Mode Gradient",
    type: "concept",
    status: "proposed",
    definition: "The measurement layer of TEG-Blue. A continuous gradient mapping four nervous system regulatory states: Connection, Protection, Control, and Domination. These are states, not personality types — they shift in response to perceived threat.",
    tags: ["core-concept", "measurement"],
  },
  {
    slug: "regulatory-state",
    title: "Regulatory State",
    type: "concept",
    status: "established",
    definition: "The nervous system's current operating mode, shaped by neuroception and expressed through physiology, cognition, and behavior. Different states enable different capacities. Health is mobility, not position — a well-regulated system moves fluidly between states; getting stuck is the problem.",
    tags: ["F1", "neuroscience", "polyvagal"],
    framework: 1,
  },
  {
    slug: "state-dependent-capacity",
    title: "State-Dependent Capacity",
    type: "concept",
    status: "established",
    definition: "The principle that cognitive, emotional, and relational abilities vary with nervous system state. What someone can perceive, feel, think, and do depends on where their system has landed. This is not metaphor — it is neurobiological reality. The inability to understand another person in a given moment may not be unwillingness; the current state may have literally reduced the neurobiological capacity to do so.",
    tags: ["F1", "neuroscience", "core-concept"],
    framework: 1,
  },
  {
    slug: "neuroception",
    title: "Neuroception",
    type: "concept",
    status: "established",
    definition: "Stephen Porges' term for the nervous system's automatic, below-conscious evaluation of safety and threat. It operates before cognition and shapes what responses are available. Neuroception evaluates experienced safety, not objective danger — a stimulus objectively safe can trigger threat response if it matches patterns associated with past danger.",
    tags: ["F1", "polyvagal", "neuroscience"],
    framework: 1,
  },
  {
    slug: "calibration",
    title: "Calibration",
    type: "concept",
    status: "established",
    definition: "The developmental process through which the nervous system learns its baseline settings for safety and threat detection. Shaped by early relational experience and attachment history. Miscalibration is not malfunction — it is accurate adaptation to an inaccurate environment. The system worked perfectly; it just learned the wrong lessons.",
    tags: ["F1", "F2", "development", "attachment"],
    framework: 1,
  },
  // ===== F2: AWARENESS TEACHES AWARENESS =====
  {
    slug: "reading-emotions",
    title: "Reading Emotions (RE)",
    type: "concept",
    status: "proposed",
    definition: "The capacity to track others' emotional states — faces, tone, body language, micro-expressions. Present at birth as automatic mirroring. Develops as accurate reading under safety conditions. The two common distortions are hypervigilant RE (scanning for threat) and instrumental RE (reading for leverage).",
    tags: ["F2", "awareness-capacity", "core-concept"],
    framework: 2,
  },
  {
    slug: "emotional-resonance",
    title: "Emotional Resonance (ER)",
    type: "concept",
    status: "proposed",
    definition: "The capacity to feel with others — emotional contagion and shared experience. Present at birth as automatic resonance. Develops as sustainable resonance under safety conditions: feeling with others without losing yourself in it. The two common distortions are flooded ER (over-identifying) and sealed ER (empathy shut-down).",
    tags: ["F2", "awareness-capacity", "core-concept"],
    framework: 2,
  },
  {
    slug: "self-emotional-awareness",
    title: "Self-Emotional Awareness (SEA)",
    type: "concept",
    status: "proposed",
    definition: "The capacity to perceive and name one's own internal states. The keystone capacity of the three. Develops when the child's emotional signals are received, reflected, and repaired when misread. Without SEA, the pre-SEA condition persists: feeling = being, external feedback = identity. SEA is the pivotal variable that determines whether cognition generates true coherence or false coherence.",
    tags: ["F2", "awareness-capacity", "core-concept"],
    framework: 2,
  },
  {
    slug: "awareness-teaches-awareness",
    title: "Awareness Teaches Awareness",
    type: "concept",
    status: "proposed",
    definition: "The organizing mechanism of F2. The awareness capacities the caregivers carry are the awareness capacities that get passed. Children calibrate to what adults embody, not what they say. The transmission channel is the nervous system, not language. This is not a moral indictment — it is a developmental mechanism: what the adult nervous system can reliably embody becomes the child's training data.",
    tags: ["F2", "mechanism", "core-concept"],
    framework: 2,
  },
  {
    slug: "co-regulation",
    title: "Co-Regulation",
    type: "concept",
    status: "proposed",
    definition: "The developmental process through which the caregiver's regulated nervous system teaches the child's nervous system Biological Restoration. The child is not being 'calmed down' — they are learning a sequence: activation, supported discharge, return. That sequence becomes the template for self-regulation. The caregiver's capacity to regulate is the child's regulatory environment.",
    tags: ["F2", "development", "regulation"],
    framework: 2,
  },
  {
    slug: "biological-restoration",
    title: "Biological Restoration",
    type: "concept",
    status: "proposed",
    definition: "The mechanism by which the body returns from threat to connection — the complete cycle: activation, response, discharge, return. Learned through co-regulation. When Biological Restoration is never learned, modes become chronic and the compass gets stuck. Can be disrupted (unpredictability), misdirected (incongruence), or blocked (invalidation).",
    tags: ["F1", "F2", "regulation", "core-concept"],
    framework: 1,
  },
  {
    slug: "true-coherence",
    title: "True Coherence",
    type: "concept",
    status: "proposed",
    definition: "The state where narrative matches felt experience because cognition has the full information set — all three awareness capacities are online. RE provides accurate data about others, ER provides felt experience of connection, SEA provides data about the self. Cognition builds with the full information set. The counterpart to false coherence.",
    tags: ["F2", "cognition", "core-concept"],
    framework: 2,
  },
  {
    slug: "tolerance-thresholds",
    title: "Tolerance Thresholds",
    type: "concept",
    status: "proposed",
    definition: "The point at which the nervous system shifts from one regulatory mode to the next. Not a value — a nervous system setting: what the body has learned it must endure to stay connected. Set in early environments. A person with flooded ER and absent SEA will feel the harm being done to them but cannot identify it as harm being done to them.",
    tags: ["F2", "regulation", "development"],
    framework: 2,
  },
  {
    slug: "identity-as-configuration",
    title: "Identity as Configuration",
    type: "concept",
    status: "proposed",
    definition: "The principle that identity is not the expression of a hidden self but a cognitive structure built around whichever awareness capacities had conditions to develop. Personality is not a type — it is a record. There is no hidden self to find. Healing is not removing a mask — it is developing the capacities that never had conditions to form.",
    tags: ["F2", "identity", "core-concept"],
    framework: 2,
  },
  {
    slug: "chronic-mode",
    title: "Chronic Mode",
    type: "concept",
    status: "proposed",
    definition: "When a mode becomes the default operating position regardless of context. The system no longer registers that other modes are safe to return to. Not malfunction — accurate adaptation to an environment where Biological Restoration was never learned. From the inside, the lock does not feel like a lock — it feels like accurate perception.",
    tags: ["F1", "F2", "regulation", "core-concept"],
    framework: 2,
  },
  // ===== F3: THE LOGIC LAYER =====
  {
    slug: "logic-layer",
    title: "Logic Layer",
    type: "concept",
    status: "proposed",
    definition: "The cognitive regulation layer that sits between the Real Self and the Role Mask. Its primary function is to maintain internal coherence under pressure. In regulated states: integrates emotion with thought, tolerates ambiguity, revises beliefs when evidence changes. In defensive states: simplifies and stabilizes, protects identity structure, filters perception through role preservation. The Logic Layer does not pursue truth as its primary goal — it pursues stability. Understanding second. Regulation first.",
    tags: ["F3", "cognition", "core-concept"],
    framework: 3,
  },
  {
    slug: "false-coherence",
    title: "False Coherence",
    type: "concept",
    status: "proposed",
    definition: "When cognition constructs a stable internal narrative that preserves identity consistency, suppresses emotional contradiction, and reduces nervous-system stress — even when that narrative no longer reflects lived reality. False coherence feels like certainty, moral clarity, being 'right,' and internal relief. This relief is physiological, not epistemic. The body calms. The mind settles. And the system learns: this story works. False coherence is not lying or manipulation — it is regulatory success at the cost of emotional truth.",
    tags: ["F3", "cognition", "core-concept"],
    framework: 3,
  },
  {
    slug: "cognitive-dissonance-reframed",
    title: "Cognitive Dissonance (Regulatory)",
    type: "concept",
    status: "proposed",
    definition: "Within TEG-Blue, cognitive dissonance is defined as a regulatory stress response, not a reasoning failure. The discomfort of contradiction is the nervous system signaling threat. When reality contradicts the Role Mask and cognition cannot integrate the contradiction without threatening coherence, dissonance reduction restores subjective stability — people prefer coherent narratives over ambiguous instability.",
    tags: ["F3", "cognition", "regulation"],
    framework: 3,
  },
  {
    slug: "narcissistic-injury-reframed",
    title: "Narcissistic Injury (Regulatory)",
    type: "concept",
    status: "proposed",
    definition: "Within TEG-Blue, narcissistic injury is redefined through a nervous-system lens. It occurs when external reality contradicts the Role Mask and cognition cannot integrate the contradiction without threatening coherence. The nervous system responds first; cognition then escalates defensive strategies (denial, projection, blame, narrative control) to restore regulation. What is often judged as 'narcissism' is frequently a nervous system in acute regulatory crisis, using the only tools it has to restore coherence. This does not excuse harm — it explains mechanism.",
    tags: ["F3", "identity", "regulation"],
    framework: 3,
  },
  {
    slug: "cognitive-rigidity",
    title: "Cognitive Rigidity",
    type: "concept",
    status: "proposed",
    definition: "A state-dependent outcome of maintaining false coherence over time. Cognitive flexibility decreases, belief systems harden, contradiction becomes threatening, and learning becomes defensive. 'This must be true, because if it isn't, the system destabilizes.' Rigidity is not stupidity or stubbornness — it is a nervous system under load. Often accompanied by chronic tension, fatigue, emotional numbing, and cognitive fog.",
    tags: ["F3", "cognition", "state-dependent"],
    framework: 3,
  },
  {
    slug: "cognitive-load",
    title: "Cognitive Load (Defensive)",
    type: "concept",
    status: "proposed",
    definition: "The substantial cognitive and physiological resources consumed by maintaining false coherence. As long as cognition is occupied with contradiction management: intelligence is constrained, learning remains defensive, perception is filtered through role preservation, creativity is limited, and repair feels threatening. Defensive load prevents full cognitive capacity from being available.",
    tags: ["F3", "cognition", "regulation"],
    framework: 3,
  },
  {
    slug: "cognitive-release",
    title: "Cognitive Release",
    type: "concept",
    status: "proposed",
    definition: "What happens when nervous-system safety increases and defensive activation decreases. Emotional signals become tolerable, and cognitive capacity becomes available for: accurate perception, learning and curiosity, creativity and play, authentic self-direction, and capacity for repair. This is not becoming someone new — it is functioning without chronic defensive load.",
    tags: ["F3", "cognition", "healing"],
    framework: 3,
  },
  // ===== F4: COLLECTIVE RULE SYSTEMS =====
  {
    slug: "threat-based-rule-internalization",
    title: "Threat-Based Rule Internalization",
    type: "concept",
    status: "proposed",
    definition: "The process by which individual defensive states scale into collective behavior, producing rule systems that stabilize groups under perceived threat. The sequence: threat activates defensive regulation → defensive states synchronize across group members → shared attention narrows toward threat cues → uncertainty-reducing behaviors are reinforced → behaviors stabilize into implicit rules → rules become 'how things are' → questioning activates threat response. Rule-following is a nervous system regulation strategy, not a reasoning choice.",
    tags: ["F4", "collective", "regulation"],
    framework: 4,
  },
  {
    slug: "six-rule-systems",
    title: "Six Rule Systems",
    type: "concept",
    status: "proposed",
    definition: "Six categories of rules that consistently emerge from threat-based internalization, each serving a distinct regulatory function: (1) Roles — identity stabilization through fixed positions; (2) Obedience — belonging protection through compliance; (3) Performance — worth verification through image; (4) Dominance — power establishment through control; (5) Punishment — boundary enforcement through pain; (6) Entitlement — resource allocation based on perceived status. These are not arbitrary categories — they represent distinct regulatory functions that rules serve.",
    tags: ["F4", "collective", "rule-systems"],
    framework: 4,
  },
  {
    slug: "rules-about-roles",
    title: "Rules About Roles",
    type: "concept",
    status: "proposed",
    definition: "Rule system that stabilizes identity by assigning fixed positions. Under threat, identity flexibility becomes costly — fixed roles provide predictability. Children learn: 'Who do I need to be to stay safe and connected?' In Pattern A, roles are held lightly; in Pattern D, others' roles are enforced to preserve one's own identity. Role rigidity often indicates early attachment disruption.",
    tags: ["F4", "identity", "rule-systems"],
    framework: 4,
  },
  {
    slug: "rules-about-obedience",
    title: "Rules About Obedience",
    type: "concept",
    status: "proposed",
    definition: "Rule system that maintains belonging by minimizing conflict and deviation. Under threat, disagreement risks expulsion, so obedience becomes a belonging-protection strategy. Critical distinction: true respect involves recognition of dignity and autonomy; obedience involves compliance regardless of consent. When compliance is called respect, control becomes normalized.",
    tags: ["F4", "belonging", "rule-systems"],
    framework: 4,
  },
  {
    slug: "rules-about-performance",
    title: "Rules About Performance",
    type: "concept",
    status: "proposed",
    definition: "Rule system that verifies worth through external validation and image management. Under threat, worth becomes something to prove rather than something inherent. Often includes a distorted definition of 'strength': never needing help, never being affected, enduring without complaint. This 'strength' is actually defensive isolation — a trauma adaptation, not healthy resilience.",
    tags: ["F4", "worth", "rule-systems"],
    framework: 4,
  },
  {
    slug: "rules-about-dominance",
    title: "Rules About Dominance",
    type: "concept",
    status: "proposed",
    definition: "Rule system that establishes power hierarchies and control allocation. Under threat, power becomes a safety strategy — control of others reduces unpredictability. Often includes 'neutrality' as a tool: remaining silent during harm, framing inaction as fairness. Neutrality in asymmetric situations is not neutral — it supports the dominant party. Clients who present as 'controlling' are often terrified.",
    tags: ["F4", "power", "rule-systems"],
    framework: 4,
  },
  {
    slug: "rules-about-punishment",
    title: "Rules About Punishment",
    type: "concept",
    status: "proposed",
    definition: "Rule system that enforces boundaries through pain rather than repair. Under threat, punishment becomes the primary boundary-enforcement mechanism. Key distinction: Punishment aims to cause suffering and ends when pain is inflicted; Accountability aims to create understanding and requires ongoing repair. Punishment reduces connection; accountability maintains it. Chronic self-blame is often internalized punishment rules.",
    tags: ["F4", "boundaries", "rule-systems"],
    framework: 4,
  },
  {
    slug: "rules-about-entitlement",
    title: "Rules About Entitlement",
    type: "concept",
    status: "proposed",
    definition: "Rule system that establishes who is owed care, attention, and resources. Some individuals learn that their needs automatically create obligations in others. Forms include: Grandiose (overt superiority, expecting service), Vulnerable/Covert (using suffering to extract care, collapse as strategy), and Transactional (keeping emotional score, expecting return on 'giving'). 'Entitled' clients often experienced early relational failure — the entitlement is a strategy to ensure needs are met when trust is absent.",
    tags: ["F4", "resources", "rule-systems"],
    framework: 4,
  },
  {
    slug: "rule-escalation",
    title: "Rule Escalation",
    type: "concept",
    status: "proposed",
    definition: "The predictable intensification of rule systems under sustained threat. Stages: Initial (informal rules, social pressure, flexibility possible) → Intermediate (rules proliferate, deviation costly, moralization begins) → Advanced (reduced tolerance, increased punishment, obedience as virtue) → Extreme (authoritarian enforcement, rule-breaking as identity threat, violence normalized). At larger scales, this explains authoritarianism not as ideological anomaly but as predictable outcome of prolonged collective threat.",
    tags: ["F4", "collective", "escalation"],
    framework: 4,
  },
  // ===== F5: THREAT-DRIVEN WORTH SORTING =====
  {
    slug: "threat-driven-worth-sorting",
    title: "Threat-Driven Worth Sorting",
    type: "concept",
    status: "proposed",
    definition: "The process by which threat-stabilized rule systems naturally generate worth hierarchies — where safety signals become filters determining who is believed, protected, and resourced. The mechanism: threat increases dependency sensitivity → validation becomes regulatory → power becomes highest safety proxy → proxies formalize into sorting rules → filter internalizes as worth/worthlessness → outcomes appear to justify original sorting. Worth-seeking is a nervous system regulation strategy, not a character flaw.",
    tags: ["F5", "hierarchy", "worth"],
    framework: 5,
  },
  {
    slug: "safety-proxy",
    title: "Safety Proxy",
    type: "concept",
    status: "proposed",
    definition: "A marker that signals reduced threat and increased protection within a given environment. Functions by reducing perceived uncertainty about a person, signaling alliance with existing power structures, indicating predictability, and conveying independence from dependency risks. Channels include: economic resources, network connections, credentials/education, presentation/aesthetics, proximity to power, and institutional endorsement. Safety proxies are not inherently harmful — they become harmful when they function as shortcuts for deciding credibility, investment, protection, and punishment.",
    tags: ["F5", "hierarchy", "signaling"],
    framework: 5,
  },
  {
    slug: "three-capitals",
    title: "Three Capitals",
    type: "concept",
    status: "proposed",
    definition: "Bourdieu's three forms of capital reframed through a nervous system lens as safety proxy categories: (1) Economic Capital — signals independence, reduced dependency risk, ability to absorb failure; (2) Social Capital — signals alliance, vouched-for status, borrowed credibility through network connections; (3) Cultural Capital — signals predictability, cultural 'fit,' familiarity with dominant norms. These capitals filter credibility before content is evaluated. In Pattern A, capitals are shared; in Pattern D, they become tools of gatekeeping and exclusion.",
    tags: ["F5", "hierarchy", "capital"],
    framework: 5,
  },
  {
    slug: "eigenvector-centrality",
    title: "Eigenvector Centrality",
    type: "concept",
    status: "proposed",
    definition: "Network theory concept explaining why proximity to power determines worth independently of contribution. Ranks nodes based on the importance of their connections, not just the number. Explains social capital's power: value is determined by connection to those already perceived as important. The algorithm fails when applied to humans because emotional intelligence isn't counted, manipulation is invisible to the metric, and the system rewards proximity to power, not wisdom or care.",
    tags: ["F5", "network", "power"],
    framework: 5,
  },
  {
    slug: "structural-filtering",
    title: "Structural Filtering",
    type: "concept",
    status: "proposed",
    definition: "When safety proxy systems stabilize, entire categories of people become systematically filtered — not as exceptions but as predictable outcomes. Groups filtered include: women (capital tied to appearance/youth), people of color (capital defined by dominant group), LGBTQIA+ (capital punishes non-conformity), neurodivergent people ('professionalism' as filter), survivors of abuse (capital destroyed by speaking up), disabled people (capitals built around able-bodied assumptions), working-class/poor, immigrants/refugees, and system disruptors. These groups represent the majority of humanity but are invisible inside capital systems.",
    tags: ["F5", "hierarchy", "exclusion"],
    framework: 5,
  },
  {
    slug: "chronic-invisibility",
    title: "Chronic Invisibility",
    type: "concept",
    status: "proposed",
    definition: "The somatic impact of repeated non-response, dismissal, and exclusion. The nervous system interprets these as danger signals, activating defensive states that become chronic. Manifestations include: nervous system (hypervigilance or shutdown), cognitive (self-doubt, imposter experience), behavioral (understating needs, overworking to prove worth), relational (anticipatory rejection), and physical (chronic tension, fatigue). Structural filtering produces measurable suffering — this is not abstract inequality but physiological cost. Chronic invisibility is not cognitive distortion; it may be accurate pattern recognition of how systems actually sort people.",
    tags: ["F5", "somatic", "exclusion"],
    framework: 5,
  },
  // ===== F6: THE BELIEF-PERCEPTION LOOP =====
  {
    slug: "bias-architecture",
    title: "Bias Architecture",
    type: "concept",
    status: "proposed",
    definition: "The interconnected system of components that together reduce perceived threat and preserve internal stability. Four components: (1) Perceptual Filters — determine what gets noticed and ignored; (2) Emotional Associations — link stimuli to threat/safety before conscious processing; (3) Identity Commitments — fuse beliefs with self-concept; (4) Reinforcement Loops — strengthen patterns through social reward and internal coherence. Bias is not a single belief but an architecture. Interventions addressing only one component often fail because the others continue supporting the bias.",
    tags: ["F6", "cognition", "perception"],
    framework: 6,
  },
  {
    slug: "emotional-logic",
    title: "Emotional Logic",
    type: "concept",
    status: "proposed",
    definition: "The governing principle of bias: 'If I believe this, I feel safer.' Bias follows emotional logic, not formal logic. When threat is active, felt stability is confused with truth. This explains why logically contradictory beliefs can coexist (if both reduce threat in different contexts), why evidence against a belief can strengthen it (if challenge triggers threat), and why emotional intensity is mistaken for accuracy (the stronger the feeling, the more 'true' it seems).",
    tags: ["F6", "cognition", "regulation"],
    framework: 6,
  },
  {
    slug: "identity-filter",
    title: "Identity Filter",
    type: "concept",
    status: "proposed",
    definition: "What happens when beliefs fuse with the Role Mask (F2). Contradiction is no longer processed as information — it becomes risk to identity, belonging, and status. The mechanism: belief becomes part of 'who I am' → challenge to belief = challenge to self → nervous system activates defense → information rejected to preserve coherence → rejection feels like 'seeing clearly' rather than defending. This is why 'being wrong' can feel existential.",
    tags: ["F6", "identity", "perception"],
    framework: 6,
  },
  {
    slug: "social-reward-loop",
    title: "Social Reward Loop",
    type: "concept",
    status: "proposed",
    definition: "The mechanism by which bias is reinforced through belonging ('You think like us'), approval ('You understand'), credibility ('You're one of the smart ones'), status ('You get it'), and protection ('We'll defend you'). The loop: belief expressed → social reward received → reward reduces threat → belief strengthened → more confident expression → more social reward → bias becomes identity and group membership signal. Group-held biases are harder to revise because the loop continuously reinforces.",
    tags: ["F6", "social", "reinforcement"],
    framework: 6,
  },
  {
    slug: "empathy-collapse",
    title: "Empathy Collapse",
    type: "concept",
    status: "proposed",
    definition: "Under threat, empathy and curiosity shut down because they increase emotional load and dissonance. Empathy requires openness (risky under threat), holding complexity (costly when resources needed for self-protection), tolerating uncertainty (dangerous when uncertainty is the problem), and revising perspective (threatening when revision destabilizes). When empathy collapses, correction is experienced as attack. The system protects the bias rather than revising it.",
    tags: ["F6", "empathy", "threat"],
    framework: 6,
  },
  {
    slug: "update-failure",
    title: "Update Failure",
    type: "concept",
    status: "proposed",
    definition: "When the Identity Filter is engaged and Empathy Collapse has occurred, the system loses capacity to update beliefs based on new information. Phenomena: evidence rejected (contradicts stabilizing narrative), correction triggers escalation (challenge experienced as threat), being 'wrong' feels existential (identity fused with belief), arguments harden position (defense strengthens commitment). Update failure is not stubbornness — it is a nervous system unable to process contradiction without destabilizing.",
    tags: ["F6", "cognition", "learning"],
    framework: 6,
  },
  {
    slug: "emotional-safety-threshold",
    title: "Emotional Safety Threshold",
    type: "concept",
    status: "proposed",
    definition: "The level of internal safety needed to tolerate contradiction without escalation or collapse. Below threshold: information rejected, correction feels humiliating, learning stalls, defense escalates. Above threshold: contradiction becomes tolerable, curiosity becomes possible, beliefs become revisable, integration can occur. The equation: Update capacity = (Internal safety + Relational safety) − (Identity threat + Belonging threat). When the right side exceeds the left, update fails.",
    tags: ["F6", "safety", "learning"],
    framework: 6,
  },
  {
    slug: "felt-truth",
    title: "Felt Truth",
    type: "concept",
    status: "proposed",
    definition: "Why bias feels like perception rather than opinion. Certainty is physiological stability, not epistemic accuracy. Intuition is pattern-matching from past experience. 'Gut feeling' is somatic marker from emotional conditioning. 'Common sense' is normalized cultural bias. 'Obviously true' means no contradiction with existing model. The sequence: stimulus triggers uncertainty → interpretation selected that reduces threat → threat reduction produces physiological relief → relief experienced as 'rightness' → rightness mistaken for accuracy.",
    tags: ["F6", "perception", "cognition"],
    framework: 6,
  },
  {
    slug: "revision-pathway",
    title: "Revision Pathway",
    type: "concept",
    status: "proposed",
    definition: "The conditions under which bias can be updated. Central principle: shame does not unlearn bias; safety does. Shame fails because moral condemnation triggers defense, public exposure activates belonging threat, intellectual correction is rejected as attack. Safety enables revision through: (1) Internal safety — regulated enough to tolerate dissonance; (2) Relational safety — connection available that doesn't require the bias; (3) Identity flexibility — self-concept not entirely fused with belief; (4) Alternative meaning — new interpretation that also reduces threat; (5) Gradual exposure — contradiction introduced within tolerance window.",
    tags: ["F6", "healing", "learning"],
    framework: 6,
  },
  // ===== F7: THE ANATOMY OF TYRANNY =====
  {
    slug: "the-crossroads",
    title: "The Crossroads",
    type: "concept",
    status: "proposed",
    definition: "The critical turning point — the shift from automatic self-protection to deliberate other-control. At some point, a person in Protection Mode notices that silence, charm, guilt, or coldness can control others' behavior. The critical shift occurs when they lean in rather than pull back. The internal question changes from 'How do I feel safe?' to 'How do I make sure this never happens again?' — and the answer shifts from self-regulation to other-control. This is the most critical intervention point in the escalation pathway.",
    tags: ["F7", "escalation", "turning-point"],
    framework: 7,
  },
  {
    slug: "escalation-pathway",
    title: "Escalation Pathway",
    type: "concept",
    status: "proposed",
    definition: "The predictable sequence from Protection to Domination: (1) Protection Mode activates — nervous system responds to perceived threat; (2) Control strategies form — person learns managing others reduces distress; (3) Control gets reinforced — strategies work, fear decreases, pattern repeats; (4) Empathy narrows then collapses — others' pain becomes noise, then obstacle, then invisible; (5) Domination stabilizes — power replaces connection as primary source of safety. This pathway is not inevitable — it requires reinforcement of control, absence of accountability, and environments that reward or tolerate escalation.",
    tags: ["F7", "escalation", "domination"],
    framework: 7,
  },
  {
    slug: "crossroads-signals",
    title: "Crossroads Signals",
    type: "concept",
    status: "proposed",
    definition: "Observable indicators that defense is becoming strategy: (1) Repair disappears — apologies become strategic rather than genuine; (2) Reality gets reframed — 'That's not what happened' becomes frequent; (3) Empathy becomes selective — compassion available for some but withheld based on strategic value; (4) Accountability triggers escalation — person naming harm becomes the problem; (5) Truth becomes tactical — honesty deployed when useful, withheld when inconvenient. These signals indicate the transition from Protection Mode to Control Mode.",
    tags: ["F7", "assessment", "escalation"],
    framework: 7,
  },
  {
    slug: "moral-disengagement",
    title: "Moral Disengagement",
    type: "concept",
    status: "proposed",
    definition: "Bandura's eight mechanisms that allow harm without guilt: (1) Moral justification — reframing harm as serving higher purpose; (2) Euphemistic labeling — sanitized language to obscure harm; (3) Advantageous comparison — comparing to worse behavior to minimize; (4) Displacement of responsibility — attributing responsibility to others/circumstances; (5) Diffusion of responsibility — spreading to dilute individual accountability; (6) Minimization of consequences — downplaying harm caused; (7) Dehumanization — denying full humanity to those harmed; (8) Attribution of blame — holding victims responsible. These emerge as the system adapts to justify ongoing control.",
    tags: ["F7", "harm", "escalation"],
    framework: 7,
  },
  {
    slug: "intervention-windows",
    title: "Intervention Windows",
    type: "concept",
    status: "proposed",
    definition: "Stage-appropriate intervention possibilities that change as escalation proceeds: Protection Mode (High possibility — safety + support), Crossroads (Moderate — accountability + connection), Control Mode (Limited — external structures + protection), Domination Mode (Very limited — containment + protection). The window closes as escalation proceeds. Treating someone in Domination Mode as if at the Crossroads wastes resources and endangers those affected. Earlier stages allow insight-based approaches; later stages require protection-focused responses.",
    tags: ["F7", "intervention", "assessment"],
    framework: 7,
  },
  {
    slug: "humiliated-fury",
    title: "Humiliated Fury",
    type: "concept",
    status: "proposed",
    definition: "The shame-rage spiral identified by Lewis, Gilligan, and Tangney. When shame becomes intolerable, it converts to rage. This explains why correction often triggers escalation rather than reflection — the feedback activates shame, shame converts to fury, and the person delivering feedback becomes the target. Violence often functions as shame management. The crossroads frequently involves a shame event; domination can be understood as 'never feel that again' enacted through control of others.",
    tags: ["F7", "shame", "escalation"],
    framework: 7,
  },
  {
    slug: "coercive-control",
    title: "Coercive Control",
    type: "concept",
    status: "proposed",
    definition: "Pattern of domination in relationships identified by Stark, Johnson, and Bancroft. Operates through ongoing pattern, not isolated incidents. Involves systematic reduction of partner's autonomy through monitoring, isolation, degradation, and enforcement. The pattern is recognizable and predictable. TEG-Blue integrates this as Domination Mode expressed in intimate relationships — specific tactics as predictable expressions of power-as-safety regulatory logic.",
    tags: ["F7", "abuse", "domination"],
    framework: 7,
  },
  {
    slug: "domination-tactics",
    title: "Domination Tactics",
    type: "concept",
    status: "proposed",
    definition: "Named patterns that maintain control while avoiding accountability: Weaponized Forgiveness ('If you really cared, you'd forgive me' — forgiveness demanded to end accountability), Demand to Move On ('Why are you still bringing that up?' — positions the person who remembers harm as the problem), False Mutuality ('We both made mistakes' — flattens power differentials, makes accountability impossible), Reputation Shield ('But they're so well-respected' — social capital protects against naming), Silence Systems ('Don't make it public' — informal rules protecting those with power from being named).",
    tags: ["F7", "tactics", "domination"],
    framework: 7,
  },
  // ===== F8: SELF-RECONNECTION =====
  {
    slug: "capacity-reconnection",
    title: "Capacity Reconnection",
    type: "concept",
    status: "proposed",
    definition: "The gradual process by which awareness capacities that were disconnected or never developed begin to come online. The adaptive identity is not an enemy to defeat — it is what cognition built with incomplete data. Premature disruption triggers defensive escalation. Cognitive understanding alone is insufficient; the capacities were shaped somatically in response to relational conditions and develop somatically in response to relational safety. Healing is not finding a hidden self — it is developing capacities that never had conditions to form.",
    tags: ["F8", "healing", "awareness-capacity"],
    framework: 8,
  },
  {
    slug: "conditions-for-return",
    title: "Conditions for Return",
    type: "concept",
    status: "proposed",
    definition: "The five conditions that enable Role Mask Loosening: (1) Felt Safety — nervous system regulation sufficient for loosening; (2) Accurate Mirroring — being seen as one actually is; (3) Discomfort Tolerance — capacity to stay present with difficulty (grief, fear, uncertainty); (4) Permission — internal/external acceptance of imperfection; (5) Time — accumulated experience rather than single insight. These conditions must be present before significant loosening can occur safely.",
    tags: ["F8", "healing", "conditions"],
    framework: 8,
  },
  {
    slug: "corrective-experience",
    title: "Corrective Experience",
    type: "concept",
    status: "proposed",
    definition: "How the nervous system updates implicit learning through experience rather than insight. Occurs when: a situation resembling original danger produces a different outcome, authenticity is met with acceptance rather than rejection, vulnerability leads to connection rather than punishment, the nervous system receives evidence that old rules no longer apply. One corrective experience rarely changes the pattern — accumulated corrective experience gradually updates implicit learning.",
    tags: ["F8", "healing", "mechanism"],
    framework: 8,
  },
  {
    slug: "doorways-to-reconnection",
    title: "Doorways to Reconnection",
    type: "concept",
    status: "proposed",
    definition: "Different pathways through which people access the Real Self: (1) Somatic Awareness — body sensation, for those disconnected from feeling; (2) Emotional Honesty — felt emotion, for those who perform emotions; (3) Values Clarification — authentic wanting, for those who don't know what they want; (4) Joy and Aliveness — spontaneous energy, for those who lost access to pleasure; (5) Self-Reparenting — internal relationship, for those with harsh inner critic; (6) Mask Mapping — cognitive understanding, for those who need to understand before feeling; (7) Grief Work — loss processing, for those avoiding mourning.",
    tags: ["F8", "healing", "pathways"],
    framework: 8,
  },
  {
    slug: "loosening-phases",
    title: "Loosening Phases",
    type: "concept",
    status: "proposed",
    definition: "The five phases of Role Mask Loosening: (1) Pre-contemplation — mask invisible, fusion complete; (2) Recognition — mask becomes visible, grief emerges; (3) Ambivalence — oscillation between mask and self; (4) Active Loosening — experiments with authenticity; (5) Integration — mask as choice rather than compulsion. Loosening is not linear — oscillation between phases is normal. Regression during loosening is not failure; it is the nervous system's natural process of testing and consolidating.",
    tags: ["F8", "healing", "process"],
    framework: 8,
  },
  {
    slug: "integration-markers",
    title: "Integration Markers",
    type: "concept",
    status: "proposed",
    definition: "Signs that the Real Self is informing life rather than just survival. Changes across domains: Self-expression (gap between inner/outer → increasing alignment), Decision-making (based on role demands → based on authentic values), Relationships (built on performance → built on authenticity), Self-talk (critical, demanding → compassionate, honest), Boundaries (absent or rigid → flexible and clear), Rest (guilt-laden → permitted without justification), Accountability (triggers collapse/defense → possible without identity threat). Integration is not a destination but a way of traveling — measured by increasing choice, not mask absence.",
    tags: ["F8", "healing", "assessment"],
    framework: 8,
  },
  {
    slug: "mask-resistance",
    title: "Mask Resistance",
    type: "concept",
    status: "proposed",
    definition: "Why the Role Mask resists loosening: (1) Fused with Survival — at nervous system level, the mask is fused with belonging, safety, and identity; (2) Reinforced by Success — professional achievement and relationships built on performance strengthen it; (3) Identity Fusion — after years of living from the mask, 'this is just who I am' reflects genuine inability to perceive separation; (4) Relational Cost Anticipation — nervous system accurately predicts that loosening may cost relationships built on performance. Mask resistance should be respected, not overcome.",
    tags: ["F8", "healing", "protection"],
    framework: 8,
  },
  {
    slug: "self-reparenting",
    title: "Self-Reparenting",
    type: "concept",
    status: "proposed",
    definition: "A doorway to reconnection that involves developing an internal relationship with oneself that provides what was missing in original caregiving. Particularly useful for those with harsh inner critics. Includes learning to offer oneself compassion, validation, protection, and permission. Not replacing the past but creating new internal resources. Supports internal secure base development — the capacity to provide one's own safety and acceptance.",
    tags: ["F8", "healing", "doorways"],
    framework: 8,
  },
  // ===== F9: NEURODIVERGENCE =====
  {
    slug: "regulatory-rhythm",
    title: "Regulatory Rhythm",
    type: "concept",
    status: "proposed",
    definition: "The characteristic way a nervous system processes sensory input, attention, emotion, and social information. Neurodivergence is not a failure of regulation but a difference in regulatory rhythm — variation in how the nervous system naturally operates. These are not deficits but different configurations across domains: attention (variable intensity vs sustained), sensory processing (low/high threshold), emotional intensity (high amplitude, extended processing), social processing (explicit vs intuitive), cognitive style (associative vs linear), and motor regulation (stimming, movement needs).",
    tags: ["F9", "neurodivergence", "variation"],
    framework: 9,
  },
  {
    slug: "system-mismatch",
    title: "System Mismatch",
    type: "concept",
    status: "proposed",
    definition: "When environmental demands exceed what a nervous system can sustainably provide. For divergent nervous systems, mismatch is often structural — built into schools, workplaces, and social norms that assume neurotypical rhythms. The same divergent nervous system may function well in one environment and struggle severely in another; the variable is context, not just neurology. Common mismatches: sustained seated attention, fluorescent lighting/noise, rapid social response, multitasking, emotional modulation demands, hidden social rules.",
    tags: ["F9", "neurodivergence", "environment"],
    framework: 9,
  },
  {
    slug: "neurodivergent-masking",
    title: "Neurodivergent Masking",
    type: "concept",
    status: "proposed",
    definition: "The strategy of suppressing authentic neurological responses and performing neurotypical behavior. Not deception or character flaw — survival regulation. The nervous system's adaptation to environments that punish authentic expression. For neurodivergent individuals, the mask has an additional layer beyond Role Mask: hiding the rhythm of the nervous system itself — suppressing stims, forcing eye contact, moderating expression, performing social fluency. Masking is learned early when authentic expression leads to rejection, punishment, or social failure.",
    tags: ["F9", "neurodivergence", "masking"],
    framework: 9,
  },
  {
    slug: "masking-costs",
    title: "Masking Costs",
    type: "concept",
    status: "proposed",
    definition: "The cumulative toll of sustained neurotypical performance across six domains: (1) Energetic — chronic fatigue, need for extended recovery; (2) Cognitive — reduced processing capacity, decision fatigue; (3) Emotional — disconnection from authentic feeling, alexithymia; (4) Somatic — chronic tension, pain, stress-related illness; (5) Relational — relationships built on false presentation; (6) Identity — confusion about who one actually is. These costs accumulate invisibly until threshold is crossed.",
    tags: ["F9", "neurodivergence", "masking"],
    framework: 9,
  },
  {
    slug: "threshold-dynamics",
    title: "Threshold Dynamics",
    type: "concept",
    status: "proposed",
    definition: "The point at which regulatory capacity is exceeded. For divergent nervous systems facing chronic mismatch and sustained masking, threshold crossing becomes predictable rather than exceptional. Formula: Threshold = Baseline capacity − (Masking cost + Environmental demand + Accumulated stress). Threshold responses include: Meltdown (emotional explosion, overwhelm, loss of control), Shutdown (withdrawal, numbness, paralysis), or Mixed (oscillation between activation and withdrawal). These are not 'overreactions' but nervous system reaching capacity limit.",
    tags: ["F9", "neurodivergence", "regulation"],
    framework: 9,
  },
  {
    slug: "neurodivergent-burnout",
    title: "Neurodivergent Burnout",
    type: "concept",
    status: "proposed",
    definition: "Distinct from general burnout. Involves: skill regression (previously manageable tasks become impossible), increased sensitivity (lower threshold for sensory/emotional input), extended recovery (weeks to months, not days), identity confusion (uncertainty about baseline capacity), and masking collapse (inability to maintain previous performance). Not caused by overwork alone but by accumulated masking cost plus chronic mismatch. Recovery requires extended environmental accommodation, not just rest.",
    tags: ["F9", "neurodivergence", "burnout"],
    framework: 9,
  },
  {
    slug: "unmasking-vs-healing",
    title: "Unmasking vs Healing",
    type: "concept",
    status: "proposed",
    definition: "Critical distinction: Unmasking is dropping neurotypical performance; Healing is being met in authentic neurological expression. These are not equivalent — unmasking without a receiving environment can increase harm. Healing requires: accommodating environment (settings that don't require neurotypical performance), accurate mirroring (being seen as divergent, not defective), internalized shame repair, grief work (mourning what was lost to masking), identity reconstruction, and relational renegotiation.",
    tags: ["F9", "neurodivergence", "healing"],
    framework: 9,
  },
  {
    slug: "variation-inclusive-design",
    title: "Variation-Inclusive Design",
    type: "concept",
    status: "proposed",
    definition: "Building systems that accommodate neurological variation from the start rather than treating divergent needs as exceptions requiring special accommodation. Seven principles: (1) Regulation First — environmental safety before performance demands; (2) Sensory Consideration — lighting, sound, space for variable sensitivity; (3) Flexible Pacing — multiple timeline options; (4) Communication Clarity — explicit expectations, reduced hidden curriculum; (5) Autonomy Respect — self-determined rhythms; (6) Multiple Modalities — various ways to engage; (7) Rest Integration — recovery built into structure.",
    tags: ["F9", "neurodivergence", "design"],
    framework: 9,
  },
  // ===== F10: GENERATIONAL TRANSMISSION =====
  {
    slug: "generational-transmission",
    title: "Generational Transmission",
    type: "concept",
    status: "proposed",
    definition: "How emotional patterns, regulatory capacities, and relational templates pass from one generation to the next through multiple simultaneous pathways. The patterns described in F1–F9 do not remain contained within individuals — they transmit across generations. Unmetabolized trauma, unloosened Role Masks, and unrepaired relational patterns become the emotional environment in which children develop. Key insight: what isn't processed gets passed on; what we metabolize, we do not transmit in the same way.",
    tags: ["F10", "generational", "transmission"],
    framework: 10,
  },
  {
    slug: "transmission-mechanisms",
    title: "Transmission Mechanisms",
    type: "concept",
    status: "proposed",
    definition: "Five pathways of generational transmission: (1) Implicit Learning — children absorb patterns through observation, co-regulation, and contingent response; (2) Co-Regulation Modeling — caregiver's regulatory capacity becomes child's template; (3) Environmental Design — caregivers create physical and emotional conditions requiring specific adaptations; (4) Epigenetic Modification — trauma exposure modifies gene expression transmissible to offspring; (5) Narrative Inheritance — family stories, silences, and meaning-making frameworks shape development. Understanding each pathway reveals specific intervention points.",
    tags: ["F10", "generational", "mechanisms"],
    framework: 10,
  },
  {
    slug: "implicit-learning-transmission",
    title: "Implicit Learning (Transmission)",
    type: "concept",
    status: "proposed",
    definition: "Learning below conscious awareness through observation and experience. Children don't decide to adopt patterns; they absorb them as 'the way things are.' What they observe: how caregiver handles distress, which emotions caregiver can tolerate, how caregiver responds to needs, how caregiver treats themselves, what caregiver values/avoids. What they learn: what to do with difficult emotions, which emotions are safe to express, whether needs are legitimate, how to treat themselves, what matters and what's dangerous.",
    tags: ["F10", "generational", "learning"],
    framework: 10,
  },
  {
    slug: "earned-security",
    title: "Earned Security",
    type: "concept",
    status: "proposed",
    definition: "Main and Hesse's finding that when caregivers process their own attachment history, their children show more secure attachment — regardless of what that history contained. This demonstrates that transmission can be interrupted through metabolization. What gets processed doesn't transmit in the same way as what remains unprocessed. Earned security shows that attachment security is not determined by history but by integration of history.",
    tags: ["F10", "attachment", "healing"],
    framework: 10,
  },
  {
    slug: "metabolization",
    title: "Metabolization",
    type: "concept",
    status: "proposed",
    definition: "The processing and integration of one's own experience that interrupts generational transmission. What we metabolize — the trauma we process, the masks we loosen, the patterns we repair — we do not pass on in the same way. Metabolization requires: awareness (seeing patterns as patterns), safety (sufficient regulation to examine difficult material), support (relationships that can hold the process), narrative coherence (making sense of one's own story), and grief (mourning what was lost and what was passed on). Healing is not just personal; it is ancestral.",
    tags: ["F10", "healing", "generational"],
    framework: 10,
  },
  {
    slug: "understanding-vs-excusing",
    title: "Understanding vs Excusing",
    type: "concept",
    status: "proposed",
    definition: "Critical distinction in generational work. Understanding: sees the systems that shaped caregivers, recognizes what they never learned, acknowledges their pain, contextualizes behavior. Excusing: minimizes impact, pretends harm wasn't real, uses their pain to erase yours, justifies behavior. The integrative position: 'I can understand why you became who you became, AND I can see what it cost me.' This enables grief for what was lost, release from waiting for acknowledgment that may never come, and agency in deciding how to relate going forward.",
    tags: ["F10", "healing", "accountability"],
    framework: 10,
  },
  {
    slug: "true-elderhood",
    title: "True Elderhood",
    type: "concept",
    status: "proposed",
    definition: "Using experience for guidance rather than age for control. True elderhood: uses experience for guidance, creates space for younger generations, earns respect, takes responsibility, supports evolution. Toxic elderhood: uses age for control, competes with younger generations, demands deference, holds grievance, resists change. True elderhood recognizes that the function of elders is to transmit wisdom and create conditions for the next generation to thrive — not to demand submission or extract compliance.",
    tags: ["F10", "generational", "elderhood"],
    framework: 10,
  },
  {
    slug: "narrative-inheritance",
    title: "Narrative Inheritance",
    type: "concept",
    status: "proposed",
    definition: "Family stories, silences, and meaning-making frameworks that shape development and transmit identity across generations. Transmits: how children understand themselves, their worth, and their place in the world. Includes spoken stories, but also what is conspicuously unspoken, what questions cannot be asked, and how family history is framed. Re-authoring family stories and naming what was silenced is an intervention point for interrupting transmission.",
    tags: ["F10", "generational", "narrative"],
    framework: 10,
  },
  // ===== F11: HUMAN PARADOXES =====
  {
    slug: "multi-rationality",
    title: "Multi-Rationality",
    type: "concept",
    status: "proposed",
    definition: "The principle that contradictions are not failures of rationality but expressions of multiple rational systems operating simultaneously. Behavior that appears paradoxical is serving multiple emotional needs at once. When multiple needs are recognized, behavior becomes multi-rational — serving several objectives simultaneously. The clinical question shifts from 'Why are you being inconsistent?' to 'What competing needs is this behavior trying to serve?'",
    tags: ["F11", "paradox", "core-concept"],
    framework: 11,
  },
  {
    slug: "competing-needs",
    title: "Competing Needs",
    type: "concept",
    status: "proposed",
    definition: "Human contradictions emerge when the emotional system holds needs that cannot be simultaneously satisfied. Core competing needs include: Connection (belonging, attachment, being seen), Protection (safety, boundaries, avoiding harm), Authenticity (Real Self expression, truth), Belonging (group membership, acceptance), and Coherence (making sense, predictability). These needs often conflict — wanting love while pushing it away, demanding honesty while punishing it, achieving success that feels empty.",
    tags: ["F11", "paradox", "needs"],
    framework: 11,
  },
  {
    slug: "paradox-cascade",
    title: "Paradox Cascade",
    type: "concept",
    status: "proposed",
    definition: "How contradictions become invisible through systematic layering: (1) Initial contradiction emerges from competing needs → (2) Logic Layer constructs explanation that hides the contradiction → (3) Role Mask develops behaviors that manage both needs → (4) Social systems reinforce the pattern through rules and worth-sorting → (5) Generational transmission passes the pattern forward as 'normal' → (6) The contradiction becomes invisible — just 'how things are.' Each framework generates characteristic paradoxes through this cascade.",
    tags: ["F11", "paradox", "mechanism"],
    framework: 11,
  },
  {
    slug: "collapse-patterns",
    title: "Collapse Patterns",
    type: "concept",
    status: "proposed",
    definition: "What happens when paradox exceeds holding capacity. Four patterns: (1) Forced Resolution — one side chosen, other suppressed; presents as rigid certainty, shadow formation; (2) Paralysis — neither side chosen, system freezes; presents as indecision, avoidance, shutdown; (3) Fragmentation — parts act without integration; presents as dissociation, switching, confusion; (4) Projection — one side located in others; presents as conflict, judgment, enemy-making. These are not character flaws but nervous system responses to uncontainable contradiction.",
    tags: ["F11", "paradox", "collapse"],
    framework: 11,
  },
  {
    slug: "holding-capacity",
    title: "Holding Capacity",
    type: "concept",
    status: "proposed",
    definition: "The ability to contain paradox without collapse. Five components: (1) Both/And Thinking — cognitive ability to hold contradictory truths; (2) Somatic Tolerance — body's ability to hold tension without discharge; (3) Temporal Flexibility — recognition that not everything requires immediate resolution; (4) Part Recognition — seeing different needs as coming from different parts, all valid; (5) Grief Capacity — ability to mourn when needs genuinely conflict. Holding capacity varies by regulatory state and can be developed through specific interventions.",
    tags: ["F11", "paradox", "capacity"],
    framework: 11,
  },
  {
    slug: "integration-vs-resolution",
    title: "Integration vs Resolution",
    type: "concept",
    status: "proposed",
    definition: "Critical distinction in paradox work. Resolution: eliminating one side, finding the 'right' answer, reducing to simplicity. Integration: holding both sides, developing capacity for complexity, living with the tension. Some paradoxes cannot be resolved — the needs genuinely conflict. The goal is not to eliminate paradox but to develop capacity to contain it. Integration enables functioning with contradiction; resolution often creates shadow and rigidity.",
    tags: ["F11", "paradox", "healing"],
    framework: 11,
  },
  {
    slug: "building-holding-capacity",
    title: "Building Holding Capacity",
    type: "concept",
    status: "proposed",
    definition: "Interventions that develop paradox tolerance: (1) Naming both sides — making competing needs explicit without forcing choice; (2) Somatic tracking — developing awareness of how body holds tension; (3) Part work — helping parts communicate rather than compete; (4) Grief facilitation — supporting mourning of what cannot be had; (5) Narrative expansion — creating stories that contain complexity; (6) Titrated exposure — gradually increasing paradox tolerance. The work is not forcing resolution but expanding capacity.",
    tags: ["F11", "paradox", "intervention"],
    framework: 11,
  },
  // ===== F12: STATE-DEPENDENT COHERENCE =====
  {
    slug: "two-information-systems",
    title: "Two Information Systems",
    type: "concept",
    status: "proposed",
    definition: "The integrative architecture underlying TEG-Blue. Two parallel systems process experience: (1) Cognitive-Logical System — processes language, abstraction, reasoning, planning; conscious, deliberate, effortful; operates in seconds to minutes; optimal for analysis, prediction, complex problem-solving. (2) Emotional-Somatic System — processes safety/threat detection, relational cues, values, needs; largely unconscious, automatic, embodied; operates in milliseconds; optimal for rapid threat detection, orienting attention, sensing relevance. The emotional-somatic system is not an obstacle to rational behavior — it determines what rational behavior is available.",
    tags: ["F12", "architecture", "core-concept"],
    framework: 12,
  },
  {
    slug: "state-dependent-coherence",
    title: "State-Dependent Coherence",
    type: "concept",
    status: "proposed",
    definition: "The organizing principle of human behavior: state precedes capacity. The nervous system state determines what cognitive, emotional, and relational capacities are available. Different states produce different capacities — not as personality but as state-dependent organization. This reframe shifts intervention from trying to override the emotional system with the cognitive system (which fails) to working with both systems appropriately. Understanding this doesn't diminish cognition — it contextualizes it.",
    tags: ["F12", "architecture", "core-concept"],
    framework: 12,
  },
  {
    slug: "timing-mismatch",
    title: "Timing Mismatch",
    type: "concept",
    status: "proposed",
    definition: "Why insight alone doesn't change behavior. By the time cognitive insight is available, the emotional-somatic system has already organized a response. Sequence: Cue detection (10-50ms) → Pattern matching (50-150ms) → Autonomic response (150-300ms) → Bodily sensation (300-500ms) → Conscious awareness (500+ms) → Narrative construction (seconds) → Insight formation (seconds to minutes). The emotional-somatic system has already acted before cognition can intervene. This is appropriate domain limitation, not failure.",
    tags: ["F12", "architecture", "timing"],
    framework: 12,
  },
  {
    slug: "cognition-domain-limits",
    title: "Cognition Domain Limits",
    type: "concept",
    status: "proposed",
    definition: "What cognition can and cannot do. Can do: understand patterns retrospectively, create insight about behavior, plan for future responses, construct meaningful narratives. Cannot do: interrupt patterns in real-time, override nervous system state, execute plans when emotional system is activated, change the underlying regulatory pattern. The clinical question shifts from 'why can't they just understand?' to 'how do we reach the emotional-somatic system?'",
    tags: ["F12", "cognition", "limits"],
    framework: 12,
  },
  {
    slug: "what-changes-patterns",
    title: "What Changes Patterns",
    type: "concept",
    status: "proposed",
    definition: "The emotional-somatic system learns through experience, not explanation. Six mechanisms that actually change patterns: (1) Sustained safety — nervous system updates templates through repeated safe experiences; (2) Somatic awareness — noticing body signals creates gap between trigger and response; (3) Co-regulation — safe relationships provide external regulation that gradually internalizes; (4) Corrective experience — new experiences contradicting old learning update templates; (5) Titrated exposure — gradual approach to triggers with sufficient resources; (6) Time and consistency — nervous system learns slowly, change requires sustained conditions.",
    tags: ["F12", "change", "intervention"],
    framework: 12,
  },
  {
    slug: "what-doesnt-work",
    title: "What Doesn't Work",
    type: "concept",
    status: "proposed",
    definition: "Approaches that fail because they target the wrong system: (1) Willpower alone — operates in cognitive system, doesn't reach emotional-somatic; (2) Insight alone — understanding doesn't change the underlying pattern; (3) Reassurance alone — words don't update neuroceptive templates; (4) Force or pressure — increases threat, moves system toward protection; (5) Shame or blame — activates defensive patterns, reduces capacity; (6) Pattern A interventions in Pattern D — state mismatch makes intervention ineffective or counterproductive.",
    tags: ["F12", "intervention", "limits"],
    framework: 12,
  },
  {
    slug: "intervention-principles",
    title: "Intervention Principles",
    type: "concept",
    status: "proposed",
    definition: "Six principles for effective intervention based on the two-system architecture: (1) Safety first — create genuine safety before expecting change; (2) Experience over explanation — provide corrective experiences, not just information; (3) Body before mind — address somatic processes, don't rely on cognition alone; (4) Relationship as regulator — use co-regulation, don't expect self-regulation before capacity exists; (5) Time and consistency — expect gradual change, provide sustained conditions; (6) State awareness — build capacity to recognize current state. Match intervention to gradient position.",
    tags: ["F12", "intervention", "principles"],
    framework: 12,
  },
  {
    slug: "threat-lock",
    title: "Threat Lock",
    type: "concept",
    status: "proposed",
    definition: "When the threat response does not resolve and persists. Repeated activation without completion teaches the system a new baseline — a learned expectation that threat is the default. The compass that should move fluidly gets stuck. Not malfunction — accurate adaptation to an environment where Biological Restoration was never learned. The person does not experience themselves as locked; they experience their mode as reality.",
    tags: ["F1", "F2", "dysregulation", "trauma"],
    framework: 1,
  },
  {
    slug: "chronic-pattern",
    title: "Chronic Pattern",
    type: "concept",
    status: "proposed",
    definition: "A rapid, involuntary shift into Pattern B triggered by present stimuli resembling past danger. The nervous system responds to the past, not the present. Occurs in milliseconds, bypasses conscious thought, and feels overwhelming or 'out of nowhere.' This is not 'overreaction' — it is the system protecting based on learned patterns.",
    tags: ["F1", "trauma", "triggers"],
    framework: 1,
  },
  {
    slug: "complexity-markers",
    title: "Complexity Markers",
    type: "concept",
    status: "proposed",
    definition: "Linguistic and behavioral signs of self-awareness, perspective-taking, and emotional differentiation. Preliminary evidence suggests they predict capacity to return to Connection when challenged.",
    tags: ["measurement", "language"],
  },
  {
    slug: "return-capacity",
    title: "Return Capacity",
    type: "concept",
    status: "proposed",
    definition: "The ability to move back toward Connection after being pushed into Protection or Control by challenge or threat. TEG-Blue's core hypothesis is that this capacity — not current state — predicts relational outcomes.",
    tags: ["core-concept", "measurement"],
  },
];

export default function GlossaryPage() {
  return (
    <div
      style={{
        minHeight: "100vh",
        background: BG.page,
        fontFamily: FONT.display,
      }}
    >
      <SiteHeader currentPath="/glossary" />

      <main
        id="main-content"
        style={{
          maxWidth: SPACING.containerMax,
          margin: "0 auto",
          padding: `32px ${SPACING.pagePadding} 60px`,
        }}
      >
        <ResearcherHero
          badge="GLOSSARY"
          title="Key Terms & Concepts"
          description="Definitions for regulatory states, complexity markers, and core framework concepts used throughout TEG-Blue research."
        />

        <GlossaryList terms={GLOSSARY_TERMS} />

        {/* Footer note */}
        <footer style={{ marginTop: 40, textAlign: "center" }}>
          <p style={{ fontSize: 11, color: TEXT.micro, fontFamily: FONT.mono }}>
            TEG-Blue Research Consortium · Open Science · CC BY-NC-SA 4.0
          </p>
        </footer>
      </main>

      <SiteFooter />
    </div>
  );
}
