import { READING } from "../mechanics-config";
import GoDeeper from "../GoDeeper";

export default function Piece02WhyPeopleChange() {
  return (
    <article>
      {/* Opening paragraphs */}
      <p style={READING.paragraph}>I{"\u2019"}ve been collecting variations of this pattern for a long time. A clinician describing a patient whose family is in crisis but whose colleagues adore them. A manager trying to understand why their most respected director leaves a trail of damage at home. Someone trying to reconcile the person they live with against the person everyone else keeps telling them they{"\u2019"}re lucky to have.</p>

      <p style={READING.paragraph}>The versions are different. The structure underneath is the same.</p>

      <p style={READING.paragraph}>What people are usually asking {"\u2014"} without quite being able to name it {"\u2014"} is whether the {"\u201C"}good{"\u201D"} version is real or the {"\u201C"}bad{"\u201D"} version is real. Which one is the actual person.</p>

      <p style={READING.paragraph}>That is the wrong question. And the reason it keeps producing confusion is that it starts from an assumption the evidence doesn{"\u2019"}t support.</p>

      <p style={READING.paragraph}>Here is what is actually happening.</p>

      <hr style={READING.hr} />

      {/* Section 1 */}
      <h2 style={READING.heading}>
        <span style={READING.sectionNumber}>1.</span> How can someone be genuinely kind in one context and genuinely terrible in another?
      </h2>

      <p style={READING.paragraph}>Because human behavior is not generated by character alone. It is generated by the interaction between a person{"\u2019"}s internal regulatory system and the conditions of their environment.</p>

      <p style={READING.paragraph}>The same person in two different contexts is not performing two different characters. They are operating in two different regulatory environments {"\u2014"} and their nervous system is responding accordingly.</p>

      <p style={READING.paragraph}>In some contexts, the environment provides regulation. There are social rules, accountability structures, reputation stakes, observed consequences. Other people{"\u2019"}s eyes do a significant portion of the regulatory work. The person doesn{"\u2019"}t need to generate all of their coherent, controlled behavior from the inside {"\u2014"} the context is generating a substantial part of it for them.</p>

      <p style={READING.paragraph}>In other contexts, those external structures are absent or inverted. The people present are not peers or superiors {"\u2014"} they are dependents, partners, family. The accountability is asymmetric or private. There is no audience evaluating performance. And in those conditions, what surfaces is whatever the nervous system produces when it isn{"\u2019"}t being held up by external scaffolding.</p>

      <p style={READING.paragraph}>This is not hypocrisy. It is not a performance in one direction or the other. Both versions are real. But one of them is partly the person, and partly the environment doing regulatory work the person cannot consistently do on their own.</p>

      <hr style={READING.hr} />

      {/* Section 2 */}
      <h2 style={READING.heading}>
        <span style={READING.sectionNumber}>2.</span> Does that mean one version is fake?
      </h2>

      <p style={READING.paragraph}>Not fake. Scaffolded.</p>

      <p style={READING.paragraph}>The {"\u201C"}good{"\u201D"} version at work is not a mask over a hidden {"\u201C"}true self{"\u201D"} underneath. The kindness, the professionalism, the competence {"\u2014"} those are real. They are genuinely produced by that person in that context.</p>

      <p style={READING.paragraph}>But what is also true is that the context is doing work. The workplace has rules, norms, consequences for violating them. It has a social structure that rewards certain behaviors and penalizes others visibly. Most people, in most professional contexts, are regulated partly by those structures without ever being consciously aware of it.</p>

      <p style={READING.paragraph}>The {"\u201C"}bad{"\u201D"} version at home is also real. It is not a suppressed truth that was always there waiting to emerge. It is what the system produces when external regulation is removed {"\u2014"} when the person is in a space where accountability is private, where relationships are close enough to absorb repeated damage without immediately rupturing, where the power dynamics don{"\u2019"}t require managing impressions.</p>

      <p style={READING.paragraph}>The question worth asking is not which version is real. It is: what does this person{"\u2019"}s behavior look like when they are not being held up by external structure? Because that version tells you something important about what the underlying system is capable of producing on its own.</p>

      <hr style={READING.hr} />

      {/* Section 3 */}
      <h2 style={READING.heading}>
        <span style={READING.sectionNumber}>3.</span> Why does the worst behavior so often happen in the closest relationships?
      </h2>

      <p style={READING.paragraph}>Several mechanisms converge here, and they tend to compound each other.</p>

      <p style={READING.paragraph}>The first is familiarity as safety signal. The nervous system reads closeness as safety {"\u2014"} and a system that is running in a chronically dysregulated mode will, paradoxically, produce its most dysregulated behavior precisely where it feels most secure. The relationship absorbs damage without immediately breaking. This is not a choice. The system has learned, often very early, that certain kinds of relationships are the appropriate place to unload what has been compressed elsewhere.</p>

      <p style={READING.paragraph}>The second is accumulated cost. The regulatory effort required to perform in a professional context is genuinely expensive. Sustained management of presentation, tone, emotional expression, and response to frustration across an eight-hour workday produces a deficit. What returns home is a system that has spent most of its regulatory resources already. The partner, the children, the family {"\u2014"} they receive what is left after the workplace has taken what it required.</p>

      <p style={READING.paragraph}>The third is structural permission. In a professional context, power is horizontal or upward-facing {"\u2014"} colleagues, managers, reputation. In a home context, power is often asymmetric {"\u2014"} toward a partner who has made commitments, toward children who have nowhere else to go, toward family relationships that have a different cost structure for rupture. The structural conditions for unchecked behavior are simply more present at home than at work.</p>

      <p style={READING.paragraph}>None of these mechanisms require bad intent. They operate beneath the level of deliberate choice, which is part of what makes them so difficult to address.</p>

      <hr style={READING.hr} />

      {/* Section 4 */}
      <h2 style={READING.heading}>
        <span style={READING.sectionNumber}>4.</span> Why do some people seem to genuinely not know how they behave at home?
      </h2>

      <p style={READING.paragraph}>Because the behavior is happening in a mode that is not self-observing.</p>

      <p style={READING.paragraph}>When a system is operating under high stress, or has shifted into a controlling or dysregulated mode, the capacity for accurate self-perception diminishes significantly. The system is not reflecting on what it is doing {"\u2014"} it is doing it. The internal experience is not {"\u201C"}I am being controlling and frightening.{"\u201D"} The internal experience is something closer to {"\u201C"}I am trying to manage a situation that keeps not cooperating.{"\u201D"}</p>

      <p style={READING.paragraph}>This produces a specific and very frustrating pattern: the person at the center of the damage is often genuinely confused by other people{"\u2019"}s distress. From inside their own experience, they were trying to be helpful, trying to solve a problem, trying to keep things from falling apart. The mismatch between their internal account and the external impact is not fabricated. It is the natural product of operating from a mode that has lost access to accurate signal reception.</p>

      <p style={READING.paragraph}>The person who is widely loved at work and reports having {"\u201C"}no idea{"\u201D"} why their family is in crisis is often telling the truth about their inner experience. They are not lying. They are describing what the system looked like from the inside {"\u2014"} which, in that mode, is genuinely not what it looked like from the outside.</p>

      <p style={READING.paragraph}>This is one of the reasons these situations are so destabilizing for the people living with them. The person who is causing harm keeps producing a coherent, well-functioning version of themselves for the outside world. That version is evidence, constantly visible, that the capacity exists. Which makes the private version feel like a choice, even when it isn{"\u2019"}t.</p>

      <hr style={READING.hr} />

      {/* Section 5 */}
      <h2 style={READING.heading}>
        <span style={READING.sectionNumber}>5.</span> Is this just about power {"\u2014"} do people behave badly when they can get away with it?
      </h2>

      <p style={READING.paragraph}>Power is one structural variable. It is not the whole explanation.</p>

      <p style={READING.paragraph}>It is true that the conditions for unchecked behavior are more present where power is asymmetric {"\u2014"} where the person experiencing the harm has fewer exits, more emotional investment, or less structural ability to enforce consequences. In that sense, yes: behavior that would be immediately sanctioned in a professional setting can persist indefinitely in a private one.</p>

      <p style={READING.paragraph}>But the framing of {"\u201C"}getting away with it{"\u201D"} implies conscious calculation that is often not present. Many people who behave very differently across contexts do not experience themselves as choosing to perform in one space and drop the performance in another. The shift is automatic. It is the nervous system responding to the structural features of the environment, not a deliberate decision to treat one set of people as less deserving of decent behavior.</p>

      <p style={READING.paragraph}>There are cases where the calculation is conscious. There are people who understand exactly what they are doing and do it because the conditions allow it. But treating that as the default explanation misses the larger group {"\u2014"} people who would be genuinely distressed to see clearly what they look like at home, and who have developed very effective ways of not seeing it.</p>

      <p style={READING.paragraph}>Power shapes the conditions. But what is running inside those conditions is a regulatory system doing what regulatory systems do {"\u2014"} expanding into available space, releasing what has been compressed, operating differently when the external scaffolding is removed.</p>

      <p style={READING.paragraph}>Understanding that does not remove accountability. A structure explaining behavior is not a structure excusing it. But it changes where the useful work is, which is not the same thing.</p>

      <hr style={READING.hr} />

      {/* Section 6 */}
      <h2 style={READING.heading}>
        <span style={READING.sectionNumber}>6.</span> Why is it so hard to convince someone that their home behavior is a problem when everyone else seems to think they{"\u2019"}re wonderful?
      </h2>

      <p style={READING.paragraph}>Because the social evidence is running in the opposite direction {"\u2014"} and social evidence is not neutral. It is regulatory.</p>

      <p style={READING.paragraph}>The feedback a person receives from a functional professional life {"\u2014"} respect from colleagues, appreciation from managers, warmth from friends {"\u2014"} is itself a form of regulation. It produces a stable, coherent internal account: I am a good person who treats people well. I am liked. I am trusted. I contribute.</p>

      <p style={READING.paragraph}>Into that account, someone close is now introducing an incompatible piece of information: that the same person is frightening, demeaning, or unreachable at home. The cost of integrating that information is not just updating a belief. It is dismantling the regulatory structure the external social evidence has been providing.</p>

      <p style={READING.paragraph}>The professional life becomes, functionally, evidence against the domestic reality. Every colleague who respects them is a counter-argument. Every friendship is a data point for the defense. The person being told they are causing harm at home has a large, coherent, socially verified case that this cannot be true {"\u2014"} and a single, private source telling them otherwise.</p>

      <p style={READING.paragraph}>This is not a conspiracy. It is not deliberate manipulation, in most cases. It is the natural operation of a system that is using social validation as a regulatory tool and cannot afford to let that tool be destabilized.</p>

      <p style={READING.paragraph}>What makes it so disorienting for the person at home is that they are effectively alone in their account. The world keeps confirming the other version. The people most positioned to see clearly are the ones with the least social credibility to make the case.</p>

      <hr style={READING.hr} />

      {/* Section 7 */}
      <h2 style={READING.heading}>
        <span style={READING.sectionNumber}>7.</span> Can this change {"\u2014"} or is context-dependent behavior just how some people are?
      </h2>

      <p style={READING.paragraph}>It can change. But not the way most people try to change it.</p>

      <p style={READING.paragraph}>The default approach is to address the behavior {"\u2014"} to name the incidents, document the pattern, deliver the feedback clearly enough that the person finally understands the impact. This approach treats the problem as an information gap. The person doesn{"\u2019"}t know how they{"\u2019"}re behaving, so better information will correct the behavior.</p>

      <p style={READING.paragraph}>The research and the structural logic both suggest this is unlikely to work on its own. The behavior is not a product of missing information. It is a product of a regulatory system that operates differently across contexts {"\u2014"} and that, in the private context, has limited capacity to self-observe, self-correct, or integrate feedback that destabilizes the existing account.</p>

      <p style={READING.paragraph}>What can shift the pattern is working at the level of the regulatory system itself, rather than at the level of the specific behaviors it is producing. This looks like building genuine internal capacity {"\u2014"} the kind that doesn{"\u2019"}t depend on external scaffolding to produce decent behavior. It looks like developing the ability to receive accurate signal about one{"\u2019"}s own impact, even when that signal is uncomfortable. It looks like understanding what the home context is triggering and why {"\u2014"} often something that was established long before the current relationships existed.</p>

      <p style={READING.paragraph}>This is slow. It requires the person at the center to be willing to look at a version of themselves they have been structurally protected from seeing. The conditions that make that possible {"\u2014"} genuine safety, the right kind of relational challenge, sometimes professional support {"\u2014"} are not always available.</p>

      <p style={READING.paragraph}>But the behavior is a product of a system. Systems can change. The question is whether the conditions for change exist, and whether the person in question can tolerate encountering themselves in the contexts where the scaffolding has been removed.</p>

      <p style={READING.paragraph}>That is a very different question from whether they are fundamentally a bad person. It is, in some ways, a harder question. But it is the one that leads somewhere.</p>

      <hr style={READING.hr} />

      {/* Framework reveal */}
      <h2 style={{ ...READING.heading, marginTop: 32 }}>The framework behind these answers</h2>

      <p style={READING.paragraph}>I kept finding this structure {"\u2014"} context-dependent behavior, regulation outsourced to environment, the worst versions appearing in the safest relationships {"\u2014"} across clinical case studies, organizational psychology research, developmental trauma literature, and systems theory. Each field had its own name for pieces of it. None of them had the whole shape.</p>

      <p style={READING.paragraph}>The framework I built to hold it is <strong>TEG-Blue {"\u2014"} The Emotional Gradient Blueprint</strong>. It treats what is described in this piece not as a character defect or a moral failure, but as a predictable output of how regulatory systems develop and operate {"\u2014"} and what happens when the conditions that support regulation are present in one context and absent in another.</p>

      <p style={READING.paragraph}>The four operating modes of M1 (Connection, Protection, Control, Domination) are not personality types. They are states any person can occupy. The mode activated in any given moment is a function of the regulatory conditions of that environment {"\u2014"} what the nervous system reads as safe, threatened, or unchecked. Context-dependent behavior is what that architecture looks like in real life.</p>

      <p style={READING.paragraph}>The full framework is available at <strong>teg-blue.org</strong> {"\u2014"} built for researchers, scientists, and those who think in systems.</p>

      <hr style={READING.hr} />

      {/* Fine print */}
      <p style={READING.finePrint}><em>TEG-Blue is an independent research framework. The models described in this piece represent a synthesis of over fifty established theories across neuroscience, trauma psychology, and systems science {"\u2014"} integrated into a navigable architecture for understanding human emotional behaviour.</em></p>

      {/* Go deeper */}
      <GoDeeper
        items={[
          {
            description: "You want to understand the four operating modes \u2014 what activates each one and what the system looks like from the inside:",
            label: "M1 \u2014 The Inner Compass & Four-Mode Gradient",
            href: "/model/m1-inner-compass",
          },
          {
            description: "You want to understand how collective rules and social structures do regulatory work \u2014 and what happens when those structures are removed:",
            label: "F4 \u2014 Collective Rules & Institutional Structures",
            href: "/framework/f4-rules-regulate",
          },
          {
            description: "You want to understand worth hierarchies \u2014 why social validation functions as regulation, and what it costs to destabilize it:",
            label: "F5 \u2014 Worth Hierarchies",
            href: "/framework/f5-worth-hierarchies",
          },
          {
            description: "You want to understand how the capacity to self-regulate develops \u2014 and why some systems became structurally dependent on external scaffolding:",
            label: "F2 \u2014 Developmental Failure of Regulation",
            href: "/framework/f2-awareness-calibration",
          },
          {
            description: "You want to understand what genuine repair looks like \u2014 the conditions under which systems can develop internal capacity rather than context-dependent performance:",
            label: "F8 \u2014 Individual Repair & The Power of Difference",
            href: "/framework/f8-repairing-awareness",
          },
        ]}
      />

      <hr style={READING.hr} />

      {/* Series footer */}
      <p style={READING.seriesFooter}>Series: Why Humans Are So Frustrating {"\u00B7"} No. 02</p>
      <p style={READING.seriesFooter}>Last updated: 2026-03</p>
    </article>
  );
}
