import { notFound } from "next/navigation";
import { BG, FONT } from "@/src/styles/tokens";
import { SiteHeader, SiteFooter } from "@/src/components";
import MechanicsLayout from "../../MechanicsLayout";
import { SERIES, findPiece } from "../../mechanics-config";
import { PIECE_COMPONENTS } from "../../_pieces";
import { generateBreadcrumbJsonLd } from "@/src/lib/jsonld";

const BASE_URL = "https://teg-blue.org";

// ─── FAQ DATA (for AEO — answer engine optimization) ───

const PIECE_FAQ = {
  "01-why-humans-are-so-frustrating": [
    { q: "What do we actually mean when we call someone frustrating?", a: "We mean they are not using the information available to them. The gap between available information and resulting behavior is almost never about information \u2014 it is about the regulatory state the person is in when the information arrives." },
    { q: "Why do smart people make such obviously bad decisions?", a: "Because the part of the brain making the decision is not the part the intelligence test measured. The limbic system responds before the prefrontal cortex is even aware there is a situation to analyze, then cognition narrates a justification." },
    { q: "Why do people keep making the same mistake even when they can see it clearly?", a: "Because seeing is done by a different system than the one making it. Knowledge lives in the cognitive system while behavior is generated by the regulatory system \u2014 and those two systems are not on a single loop." },
    { q: "Why do people believe things that are obviously false?", a: "Because when a belief is doing regulatory work \u2014 holding a frightening world in a manageable shape \u2014 the cognitive system evaluates evidence in the context of what dismantling the belief would cost, not whether the evidence is accurate." },
    { q: "Why do people stay in situations that are obviously bad for them?", a: "Because leaving is a regulatory calculation, not a cognitive one. The familiar \u2014 even the familiarly harmful \u2014 registers as safer than the unfamiliar for a nervous system trained to read uncertainty as more dangerous than known harm." },
    { q: "Why do people know exactly what they need to do and not do it?", a: "Because knowing what to do and being in a state that can do it are two different things. The person is caught between a cognitive system that has accurate information and a regulatory system that has more authority over the body." },
    { q: "Is there anything that actually bridges the gap between knowledge and behavior?", a: "Yes, but it is not more knowledge. Everything that reliably produces behavioral change works by changing the regulatory state through safe repetition, relationship, body-first approaches, and tolerance for the gap between knowing and doing." },
  ],
  "01-why-evidence-fails": [
    { q: "Why doesn\u2019t evidence work to change people\u2019s minds?", a: "Because the person is not running an evidence-processing system in that moment. When a belief functions as a regulatory tool, evidence lands as threat \u2014 and a threatened system defends rather than updates." },
    { q: "Are conspiracy believers less intelligent or less educated?", a: "No. Intelligence does not protect against motivated belief. Higher verbal intelligence can correlate with greater capacity to construct sophisticated defenses for beliefs already held." },
    { q: "Are conspiracy believers doing this consciously?", a: "Mostly no. The belief is genuinely held through a filtering process so automatic that contrary evidence rarely arrives in its unmodified form." },
    { q: "Why do people get more entrenched when pushed harder?", a: "Because pressure on a regulatory system produces more regulation, not less. When a belief functions as a stabilizing structure, the system responds to external threats by reinforcing." },
    { q: "Is there a pattern to which conspiracy theories people believe?", a: "Yes \u2014 the pattern follows function, not content. People adopt conspiracy beliefs in domains where their unmet needs are highest: belonging, competence, coherence, or institutional trust." },
    { q: "Is there anything that actually works to change conspiracy beliefs?", a: "Yes, but it requires starting somewhere other than the evidence. Everything effective has one thing in common: it reduces the threat before introducing the challenge." },
    { q: "Should I keep trying to convince someone who believes conspiracy theories?", a: "If the goal is visible immediate acknowledgment you were right, that outcome is rare. But modeling a different way of engaging with uncertainty and staying in contact \u2014 those are possible." },
  ],
  "02-why-people-change-by-context": [
    { q: "How can someone be genuinely kind in one context and genuinely terrible in another?", a: "Because behavior is generated by the interaction between a person\u2019s regulatory system and environmental conditions. Both versions are real, but one is partly the person and partly the environment doing regulatory work the person cannot do alone." },
    { q: "Does that mean one version of the person is fake?", a: "Not fake \u2014 scaffolded. The good version at work is real but supported by external structures. The version at home is what the system produces when external regulation is removed." },
    { q: "Why does the worst behavior happen in the closest relationships?", a: "Several mechanisms converge: the nervous system reads closeness as safety and unloads what was compressed elsewhere, the regulatory effort of performing professionally creates a deficit, and asymmetric power at home permits unchecked behavior." },
    { q: "Why do some people genuinely not know how they behave at home?", a: "Because the behavior happens in a mode that is not self-observing. Under high stress or in a controlling mode, accurate self-perception diminishes \u2014 the internal experience does not match the external impact." },
    { q: "Is context-dependent behavior just about power?", a: "Power is one variable, not the whole explanation. The shift is often automatic \u2014 the nervous system responding to structural features of the environment, not a deliberate decision to treat certain people worse." },
    { q: "Why is it hard to convince someone their home behavior is a problem?", a: "Because the social evidence from their professional life runs in the opposite direction. Every colleague who respects them becomes a counter-argument against the private reality." },
    { q: "Can context-dependent behavior change?", a: "Yes, but not by addressing the behavior directly. Change requires working at the level of the regulatory system itself \u2014 building genuine internal capacity that doesn\u2019t depend on external scaffolding." },
  ],
};

// ─── STATIC PARAMS ──────────────────────────────────

export function generateStaticParams() {
  const params = [];
  for (const series of SERIES) {
    for (const piece of series.pieces) {
      params.push({
        seriesSlug: series.slug,
        pieceSlug: piece.slug,
      });
    }
  }
  return params;
}

// ─── METADATA ───────────────────────────────────────

export async function generateMetadata({ params }) {
  const { seriesSlug, pieceSlug } = await params;
  const found = findPiece(pieceSlug);
  if (!found || found.series.slug !== seriesSlug) return { title: "Not Found" };

  const { piece, series } = found;
  const url = `${BASE_URL}/mechanics-of-phenomena/${seriesSlug}/${pieceSlug}`;

  return {
    title: `${piece.title} | TEG-Blue`,
    description: piece.metaDescription || piece.subtitle,
    alternates: { canonical: url },
    openGraph: {
      title: `${piece.title} | ${series.name}`,
      description: piece.metaDescription || piece.subtitle,
      url,
      type: "article",
      siteName: "TEG-Blue Research",
    },
  };
}

// ─── PAGE ───────────────────────────────────────────

export default async function MechanicsPiecePage({ params }) {
  const { seriesSlug, pieceSlug } = await params;
  const found = findPiece(pieceSlug);
  if (!found || found.series.slug !== seriesSlug) notFound();

  const { piece, series } = found;
  const PieceComponent = PIECE_COMPONENTS[pieceSlug];
  if (!PieceComponent) notFound();

  const pieceUrl = `${BASE_URL}/mechanics-of-phenomena/${seriesSlug}/${pieceSlug}`;

  // JSON-LD: Article
  const articleJsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: piece.title,
    description: piece.metaDescription || piece.subtitle,
    author: {
      "@type": "Person",
      name: "Anna Paretas-Artacho",
    },
    publisher: {
      "@type": "Organization",
      name: "TEG-Blue Research",
      url: BASE_URL,
    },
    url: pieceUrl,
    isPartOf: {
      "@type": "CreativeWorkSeries",
      name: series.name,
      url: `${BASE_URL}/mechanics-of-phenomena`,
    },
    // Speakable: tells voice assistants which sections to read
    speakable: {
      "@type": "SpeakableSpecification",
      cssSelector: ["article > p:first-of-type", "article h2", "article h2 + p"],
    },
  };

  // JSON-LD: Breadcrumbs
  const breadcrumbJsonLd = generateBreadcrumbJsonLd([
    { name: "Research", url: "/" },
    { name: "Mechanics of Phenomena", url: "/mechanics-of-phenomena" },
    { name: series.name, url: `/mechanics-of-phenomena#${seriesSlug}` },
    { name: piece.title, url: `/mechanics-of-phenomena/${seriesSlug}/${pieceSlug}` },
  ]);

  // JSON-LD: FAQ (for answer engine optimization)
  const faqItems = PIECE_FAQ[pieceSlug];
  const faqJsonLd = faqItems
    ? {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        mainEntity: faqItems.map(({ q, a }) => ({
          "@type": "Question",
          name: q,
          acceptedAnswer: {
            "@type": "Answer",
            text: a,
          },
        })),
      }
    : null;

  return (
    <div style={{ minHeight: "100vh", background: BG.page, fontFamily: FONT.display }}>
      <SiteHeader currentPath="/mechanics-of-phenomena" />

      <MechanicsLayout
        activePiece={pieceSlug}
        showBackLink={true}
        articleSections={piece.sections}
      >
        <PieceComponent />
      </MechanicsLayout>

      <SiteFooter />

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      {faqJsonLd && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
        />
      )}
    </div>
  );
}
