import dynamic from "next/dynamic";
import Link from "next/link";
import { BG, TEXT, FONT, SPECTRUM, PATTERN, hexToRgba } from "@/src/styles/tokens";
import { SiteHeader, SiteFooter, ModelHero, ExpandableSection, PageLayout, PartDivider, NavSection, ConnectionsMap } from "@/src/components";

const M4SystemsDiagram = dynamic(() => import("@/src/components/M4SystemsDiagram"), { ssr: false });
const M4AwarenessDiagram = dynamic(() => import("@/src/components/M4AwarenessDiagram"), { ssr: false });
import { proseStyle, expandedProseStyle, propositionItemStyle, sectionHeadingStyle, conceptHeadingStyle, expandableRowStyle, gridHeaderStyle, gridCellStyle } from "@/src/styles/pageStyles";
import { generateBreadcrumbJsonLd, generateFAQJsonLd, generateSpeakableJsonLd } from "@/src/lib/jsonld";
const P = { A: PATTERN.A.primary, B: PATTERN.B.primary, C: PATTERN.C.primary, D: PATTERN.D.primary };
const linkStyle = { color: P.B, textDecoration: "none" };
export const metadata = { title: "Awareness Capacities (M4) | TEG-Blue Research", description: "What determines whether the person can perceive the Emotional Somatic Cycle while it is running. Two systems, two substrates, three awareness capacities.", keywords: ["awareness capacities","interoceptive self-awareness","affective resonance","interpersonal affect perception","interoceptive access","two substrates","empathy architecture"], alternates: { canonical: "https://teg-blue.org/model/m4-awareness-capacities" }, openGraph: { title: "Awareness Capacities \u2014 M4 Model | TEG-Blue", description: "Two systems, two substrates, three awareness capacities.", url: "https://teg-blue.org/model/m4-awareness-capacities", type: "article", siteName: "TEG-Blue Research" }, twitter: { card: "summary_large_image", title: "Awareness Capacities \u2014 TEG-Blue M4", description: "The biological architecture of self-awareness." }, other: { "citation_title": "Awareness Capacities", "citation_author": "Anna Paretas-Artacho", "citation_publication_date": "2026/02", "citation_technical_report_institution": "TEG-Blue Research" } };
export default function M4AwarenessCapacitiesPage() { return (<div style={{ minHeight: "100vh", background: BG.page, fontFamily: FONT.display }}><SiteHeader currentPath="/model/m4-awareness-capacities" /><PageLayout header={<ModelHero badge="MODEL M4" title="Awareness Capacities" subtitle="The Calibration" description="Some people read others with precision — identifying emotional states in a room before anyone has spoken. The same people may have no access to what they themselves are feeling. Some people feel others intensely — and cannot distinguish that resonance from their own internal state. These are not variations of one capacity. They are three distinct awareness capacities, each built on different biological hardware, each with a different vulnerability under chronic stress. This model maps the architecture that determines what can be perceived — and what runs unseen." coreQuestion="Can the person feel any of these physiological changes while they are happening?" drawsFrom={[{ label: "M1", href: "/model/m1-emotions-as-signals" },{ label: "M2", href: "/model/m2-nervous-system-states" },{ label: "M3", href: "/model/m3-regulation-capacities" },{ label: "F2", href: "/framework/f2-awareness-calibration" }]} color={P.A} />}>

<M4SystemsDiagram />

<article>

<section style={{ marginBottom: 48 }}>
<p style={proseStyle}>The nervous system generates physiological responses continuously — hormones shift, muscles activate, heart rate changes, neural circuits reorganize. These changes carry specific information. But whether that information reaches conscious awareness is not guaranteed. The body may be running a full emotional sequence while the mind constructing the narrative has no access to it.</p>
<p style={proseStyle}>Awareness depends on more than attention or reflection. It depends on what data can reach cognition. Two information systems operate through two separate biological substrates. One reads the body from the inside — the interoceptive substrate. The other reads other bodies from the outside — the external observation substrate. They do not share hardware. When one degrades, capacities built on it degrade together while the other remains unaffected.</p>
<p style={proseStyle}>This architecture produces three distinct awareness capacities. One reads emotional states in others through observable signals. Another registers those states somatically — experiencing a version of what the other person is feeling. A third allows the body{"'"}s own physiological signals to enter conscious processing. These are not variations of one general ability. They are built on different biological routes and subject to different forms of disruption.</p>
<p style={proseStyle}>The central finding is that access to the body{"'"}s own internal signals — the interoceptive channel — determines the awareness architecture downstream. It shapes what data reaches cognition, what kind of coherence cognition can build from that data, and whether an emotional sequence running below awareness remains invisible or becomes knowable.</p>
</section>


<section id="core-propositions" aria-labelledby="heading-cp" style={{ marginBottom: 48 }}><h2 id="heading-cp" style={sectionHeadingStyle(P.A)}>Core Propositions</h2><ul style={{ paddingLeft: 20, margin: 0 }}>
<li style={propositionItemStyle}>What the culture calls empathy is three distinct awareness capacities — each accessing different information, each operating through different biological channels, each with a different vulnerability under chronic activation.</li>
<li style={propositionItemStyle}>Two information systems — the ESS and the CLS — operate through two separate substrates. The interoceptive substrate reads the body from the inside. The external observation substrate reads other bodies from the outside. They do not share hardware.</li>
<li style={propositionItemStyle}>Interoceptive access is the single upstream variable. Its state determines which capacities can function, what data reaches the CLS, what coherence the CLS builds, and whether the person can observe the ESS running.</li>
<li style={propositionItemStyle}>RE (reading others) survives and sharpens under chronic activation. ER (feeling others) degrades first. SEA (feeling oneself) is the bridge between the two systems — and the bridge the pattern closes.</li>
<li style={propositionItemStyle}>The CLS builds coherence from whatever data it has. Without the bridge, it builds from incomplete data — and the coherence feels complete.</li>
<li style={propositionItemStyle}>The bridge needed to see the pattern is the bridge the pattern closes.</li>
<li style={propositionItemStyle}>The chain feeds itself in both directions. Degradation amplifies degradation. Restoration amplifies restoration.</li>
</ul></section>

<PartDivider label="PART 1" title="What Awareness Runs On" color={P.A} />

<section id="architecture-of-empathy" aria-labelledby="heading-ae" style={{ marginBottom: 48 }}><h2 id="heading-ae" style={sectionHeadingStyle(P.A)}>The Architecture of Empathy</h2>
<p style={proseStyle}>Some people read others with precision — they identify emotional states in the room before anyone has spoken. The same people may have no access to what they themselves are feeling.</p>
<p style={proseStyle}>Some people feel others intensely — when someone nearby is in pain, they experience a version of that pain in their own body. The same people may be unable to distinguish that resonance from their own internal state.</p>
<p style={proseStyle}>Some people can observe their own emotional responses while the responses are happening. Others are inside the response with no observing position from which to see it.</p>
<p style={proseStyle}>These are not variations of one capacity. They are three distinct awareness capacities — <strong style={{ color: TEXT.primary }}>Interpersonal Affect Perception (RE)</strong>, <strong style={{ color: TEXT.primary }}>Affective Resonance (ER)</strong>, and <strong style={{ color: TEXT.primary }}>Interoceptive Self-Awareness (SEA)</strong> — each with a different biological basis, each with a different degradation pattern, and each developable through specific relational conditions.</p>
<div style={expandableRowStyle}><ExpandableSection title="Research Foundations" type="opendata"><p style={expandedProseStyle}>Decety & Jackson (2004) — empathy as multi-component. Blair (2005) — dissociable empathy components with independent degradation patterns.</p></ExpandableSection><ExpandableSection title="What TEG-Blue Adds" type="opendata"><p style={expandedProseStyle}>The reframe from degree to structure: the question is not how much empathy a person has, but which specific capacities are present and which are absent.</p></ExpandableSection></div></section>

<section id="awareness-architecture" aria-labelledby="heading-aa" style={{ marginBottom: 48 }}><h2 id="heading-aa" style={sectionHeadingStyle(P.A)}>The Awareness Architecture</h2>
<p style={proseStyle}>The nervous system operates through two information systems. The <strong style={{ color: TEXT.primary }}>Emotional Somatic System (ESS)</strong> detects, evaluates, and generates physiological responses below conscious awareness. The <strong style={{ color: TEXT.primary }}>Cognitive-Logical System (CLS)</strong> produces language, reasoning, planning, and narrative. The CLS builds from whatever data it has — and does not distinguish between a complete data set and an incomplete one.</p>
<p style={proseStyle}>The question that determines everything M4 maps: <strong style={{ color: TEXT.primary }}>what data reaches the CLS?</strong></p>
<div style={{ overflowX: "auto", marginBottom: 20 }}><div style={{ display: "grid", gridTemplateColumns: "1.2fr 1.2fr 2fr 1fr", minWidth: 600 }}>
<div style={gridHeaderStyle(P.A)}>Data Source</div><div style={gridHeaderStyle(P.A)}>Channel</div><div style={gridHeaderStyle(P.A)}>What It Provides</div><div style={gridHeaderStyle(P.A)}>Interoceptive?</div>
<div style={{ ...gridCellStyle, fontWeight: 600, color: TEXT.primary }}>External observation</div><div style={gridCellStyle}>RE</div><div style={gridCellStyle}>What other bodies are broadcasting — faces, voices, behaviour</div><div style={gridCellStyle}>No</div>
<div style={{ ...gridCellStyle, fontWeight: 600, color: TEXT.primary }}>Somatic resonance</div><div style={gridCellStyle}>ER</div><div style={gridCellStyle}>What other bodies{"'"} states feel like in one{"'"}s own body</div><div style={gridCellStyle}>Yes</div>
<div style={{ ...gridCellStyle, fontWeight: 600, color: TEXT.primary }}>Own body{"'"}s signals</div><div style={gridCellStyle}>SEA</div><div style={gridCellStyle}>What the ESS is doing right now — hormonal shifts, muscular tension, autonomic state</div><div style={gridCellStyle}>Yes</div>
<div style={{ ...gridCellStyle, fontWeight: 600, color: TEXT.primary }}>Its own output</div><div style={gridCellStyle}>(default)</div><div style={gridCellStyle}>Reasoning, narrative, abstraction, memory</div><div style={gridCellStyle}>No</div>
</div></div>
<p style={proseStyle}>Two substrates. The <strong style={{ color: TEXT.primary }}>interoceptive substrate</strong> — anterior insula, ventral vagal pathways, visceral afferents — reads the body from the inside. The <strong style={{ color: TEXT.primary }}>external observation substrate</strong> — amygdala and prefrontal cortex — reads other bodies from the outside. They do not share components. If one degrades, capacities on it degrade together while the other substrate is unaffected.</p>
<div style={expandableRowStyle}><ExpandableSection title="Research Foundations" type="opendata"><p style={expandedProseStyle}>Craig (2002, 2009) — the anterior insula as the cortical seat of interoceptive awareness. Porges (2011) — ventral vagal pathways suppressed under chronic sympathetic activation. Shamay-Tsoory et al. (2009) — double dissociation between cognitive and affective empathy.</p></ExpandableSection><ExpandableSection title="What TEG-Blue Adds" type="opendata"><p style={expandedProseStyle}>The two-system, two-substrate architecture as the structural foundation for awareness. The prediction: when one substrate degrades, capacities built on it degrade together while the capacity on the other substrate is unaffected.</p></ExpandableSection></div></section>

<section id="interoceptive-access" aria-labelledby="heading-ia" style={{ marginBottom: 48 }}><h2 id="heading-ia" style={sectionHeadingStyle(P.A)}>Interoceptive Access</h2>
<p style={proseStyle}>Interoceptive access is the state of the interoceptive substrate — whether it is generating readable signals. It is not a capacity. It is a precondition — the ceiling that determines what ER and SEA can do.</p>
<p style={proseStyle}><strong style={{ color: TEXT.primary }}>Fully available.</strong> The ESS generates signals — and the CLS knows. Override is a choice.</p>
<p style={proseStyle}><strong style={{ color: TEXT.primary }}>Absent.</strong> The ESS generates signals — and the CLS does not know. The override runs without being experienced as an override.</p>
<p style={proseStyle}><strong style={{ color: TEXT.primary }}>Partial — flooded or contradicted.</strong> The signals are either overwhelming or distrusted. The body says one thing. The narrative says another.</p>
<p style={proseStyle}>The ESS does not change across any state of interoceptive access. Interoceptive access determines one thing: whether the CLS knows the ESS is running.</p>
<p style={{ ...proseStyle, fontFamily: FONT.mono, fontSize: 12, color: TEXT.muted, padding: "12px 16px", background: hexToRgba(P.A, 0.06), borderRadius: 6, lineHeight: 1.8 }}>Interoceptive substrate → Interoceptive access → Which capacities can function → What data reaches the CLS → What the CLS builds → Whether override is visible or invisible → Whether the restoration sequence can be observed</p>
<div style={expandableRowStyle}><ExpandableSection title="Research Foundations" type="opendata"><p style={expandedProseStyle}>Craig (2002, 2009) — interoceptive accuracy as measurable. Khalsa et al. (2018) — interoceptive accuracy distinct from sensibility. van der Kolk (2014) — chronic stress reducing interoceptive access. Porges (2011) — ventral vagal suppression.</p></ExpandableSection><ExpandableSection title="What TEG-Blue Adds" type="opendata"><p style={expandedProseStyle}>Interoceptive access as the single upstream variable. The degradation order: ER first (highest substrate demand), then SEA. RE unaffected.</p></ExpandableSection></div></section>

<PartDivider label="PART 2" title="The Three Capacities" color={P.B} />

<section id="interpersonal-affect-perception" aria-labelledby="heading-re" style={{ marginBottom: 48 }}><h2 id="heading-re" style={sectionHeadingStyle(P.B)}>Interpersonal Affect Perception (RE)</h2>
<p style={proseStyle}>RE is the capacity to identify what other people are feeling through observable signals. A CLS capacity on the external observation substrate. Two-stage: rapid automatic reading (amygdala, milliseconds) + deliberate integration (prefrontal cortex, context).</p>
<p style={proseStyle}>Most robust of the three. Survives and sharpens under chronic activation — because its substrate is unaffected, and when the interoceptive substrate degrades, all cognitive resources concentrate on the one remaining channel.</p>
<p style={proseStyle}>What changes under chronic activation is not the accuracy of the reading but what the reading serves. The same capacity that in safety reads for understanding, in chronic states reads for survival, strategy, or control.</p>
<p style={proseStyle}>A person with strong RE can identify what every person in the room is feeling. This tells you nothing about whether they can feel what those people are feeling (ER). And nothing about whether they can identify what they themselves are feeling (SEA).</p>
<div style={expandableRowStyle}><ExpandableSection title="Research Foundations" type="opendata"><p style={expandedProseStyle}>Baron-Cohen (2003) — cognitive empathy as distinct and dissociable. LeDoux (1996) — amygdala processing before conscious awareness. Shamay-Tsoory et al. (2009) — double dissociation.</p></ExpandableSection><ExpandableSection title="What TEG-Blue Adds" type="opendata"><p style={expandedProseStyle}>RE as a CLS capacity on the external observation substrate — explaining why it survives and sharpens. RE sharpens not despite the loss of the other channels but because of it.</p></ExpandableSection></div></section>

<section id="affective-resonance" aria-labelledby="heading-er" style={{ marginBottom: 48 }}><h2 id="heading-er" style={sectionHeadingStyle(P.B)}>Affective Resonance (ER)</h2>
<p style={proseStyle}>ER is the capacity to feel what other people are feeling — not reading from outside, but experiencing a version of it in one{"'"}s own body. An ESS capacity on the interoceptive substrate. The body resonates before any decision or interpretation occurs.</p>
<p style={proseStyle}>Most fragile of the three. Degrades first and most completely — because it places the greatest demands on the interoceptive substrate (cross-body translation).</p>
<p style={proseStyle}>The boundary between self and other is not maintained by ER alone. That boundary requires SEA functioning simultaneously. When SEA is absent, ER has no anchor — and what appears as deep empathy may be structural merger.</p>
<p style={proseStyle}>The difference between RE and ER is not degree. It is kind. RE identifies: {"\u201C"}this person is afraid.{"\u201D"} ER produces: the body generates a version of that fear. One is information. The other is experience.</p>
<div style={expandableRowStyle}><ExpandableSection title="Research Foundations" type="opendata"><p style={expandedProseStyle}>Singer & Klimecki (2014) — empathic distress vs compassion. Porges (2011) — ventral vagal pathways suppressed under threat. Schore (2003) — right-brain relational regulation.</p></ExpandableSection><ExpandableSection title="What TEG-Blue Adds" type="opendata"><p style={expandedProseStyle}>ER as an ESS capacity — explaining its fragility. The boundary between self and other maintained by SEA, not by ER itself.</p></ExpandableSection></div></section>

<section id="interoceptive-self-awareness" aria-labelledby="heading-sea" style={{ marginBottom: 48 }}><h2 id="heading-sea" style={sectionHeadingStyle(P.B)}>Interoceptive Self-Awareness (SEA)</h2>
<p style={proseStyle}>SEA occupies a structurally unique position. It operates through the interoceptive substrate but does something neither RE nor ER can do: it connects the two systems. When the bridge is open, the CLS knows what the ESS is doing. When the bridge is closed, the CLS continues operating with no awareness that the ESS is running a sequence underneath.</p>
<p style={proseStyle}>The question SEA answers: <strong style={{ color: TEXT.primary }}>what am I feeling, right now, in my own body?</strong></p>
<p style={proseStyle}>When SEA is online, the person can register activation as information — hold it as something they are experiencing, not something they are. When SEA is absent, the person is inside the response with no observing position.</p>
<h3 style={conceptHeadingStyle}>The Family Lineage</h3>
<p style={proseStyle}>ER and SEA are two applications of the same interoceptive access — one directed outward, one directed inward. SEA is the developmental entry point: a person cannot feel others accurately if they cannot feel themselves. Building the inward channel activates the substrate for outward use. The reverse is not symmetrical.</p>
<div style={expandableRowStyle}><ExpandableSection title="Research Foundations" type="opendata"><p style={expandedProseStyle}>Craig (2002) — interoceptive awareness as substrate of self-awareness. Damasio (1999) — self-referential emotional processing. Lane & Schwartz (1987) — levels of emotional awareness. Schore (2003) — right-hemisphere self-regulatory development.</p></ExpandableSection><ExpandableSection title="What TEG-Blue Adds" type="opendata"><p style={expandedProseStyle}>SEA as the bridge between the two systems. The family lineage: substrate as parent, ER and SEA as two applications. The SEA → ER developmental direction.</p></ExpandableSection></div></section>

<M4AwarenessDiagram />

<PartDivider label="PART 3" title="What the Chain Determines" color={P.C} />

<section id="what-sea-determines" aria-labelledby="heading-wsd" style={{ marginBottom: 48 }}><h2 id="heading-wsd" style={sectionHeadingStyle(P.C)}>What Self-Awareness Determines</h2>
<p style={proseStyle}>SEA is the only capacity that connects the two systems. This connection — or its absence — determines five things:</p>
<ul style={{ paddingLeft: 20, margin: "0 0 16px" }}>
<li style={propositionItemStyle}><strong style={{ color: TEXT.primary }}>Whether the person can observe their own activation</strong></li>
<li style={propositionItemStyle}><strong style={{ color: TEXT.primary }}>Whether the person can distinguish self from other</strong></li>
<li style={propositionItemStyle}><strong style={{ color: TEXT.primary }}>Whether the person can observe override</strong></li>
<li style={propositionItemStyle}><strong style={{ color: TEXT.primary }}>Whether the person can distinguish a substitute from genuine restoration</strong></li>
<li style={propositionItemStyle}><strong style={{ color: TEXT.primary }}>Whether the Emotional Somatic Cycle can be observed while it is running</strong></li>
</ul>
<p style={proseStyle}><strong style={{ color: TEXT.primary }}>The paradox.</strong> The capacity needed to observe the pattern is the capacity the pattern degrades. The bridge closes not because the person chose to close it, but because the chronic activation that produces the pattern also degrades the biological substrate the bridge needs to function.</p>
<div style={expandableRowStyle}><ExpandableSection title="Research Foundations" type="opendata"><p style={expandedProseStyle}>Craig (2002) — interoceptive awareness linking affective resonance and self-awareness. Damasio (1999) — self-referential processing distinct from other-referential.</p></ExpandableSection><ExpandableSection title="What TEG-Blue Adds" type="opendata"><p style={expandedProseStyle}>The five-function mapping. The paradox: the bridge needed to see the pattern is the bridge the pattern closes.</p></ExpandableSection></div></section>

<section id="coherence" aria-labelledby="heading-coh" style={{ marginBottom: 48 }}><h2 id="heading-coh" style={sectionHeadingStyle(P.C)}>Coherence From Available Data</h2>
<p style={proseStyle}>The CLS builds a narrative from whatever data it has. Three states of interoceptive access produce three forms of coherence.</p>
<div style={{ overflowX: "auto", marginBottom: 20 }}><div style={{ display: "grid", gridTemplateColumns: "1.5fr 2fr 2fr 2fr", minWidth: 700 }}>
<div style={gridHeaderStyle(P.C)}></div><div style={gridHeaderStyle(P.C)}>Aligned with the body</div><div style={gridHeaderStyle(P.C)}>Without the body</div><div style={gridHeaderStyle(P.C)}>Contested by the body</div>
<div style={{ ...gridCellStyle, fontWeight: 600, color: TEXT.primary }}>Data</div><div style={gridCellStyle}>All three channels open</div><div style={gridCellStyle}>Incomplete access + cognitive replacement</div><div style={gridCellStyle}>Flooded/contradicted channels</div>
<div style={{ ...gridCellStyle, fontWeight: 600, color: TEXT.primary }}>Feels like</div><div style={gridCellStyle}>{"\u201C"}Complex and I can hold it{"\u201D"}</div><div style={gridCellStyle}>{"\u201C"}Clear and I know who I am{"\u201D"}</div><div style={gridCellStyle}>{"\u201C"}Something is wrong but I don{"'"}t know what{"\u201D"}</div>
<div style={{ ...gridCellStyle, fontWeight: 600, color: TEXT.primary }}>Function</div><div style={gridCellStyle}>Understanding</div><div style={gridCellStyle}>Regulation</div><div style={gridCellStyle}>Neither — caught between</div>
<div style={{ ...gridCellStyle, fontWeight: 600, color: TEXT.primary }}>Cost</div><div style={gridCellStyle}>Complexity</div><div style={gridCellStyle}>Truth</div><div style={gridCellStyle}>Trust</div>
</div></div>
<p style={proseStyle}>Contested coherence may be the most clinically significant. The substrate is still active. The signal is still arriving. The person is not fully disconnected — they are in conflict with their body. This is the entry point.</p>
<p style={proseStyle}>Coherence without the body often looks more put-together than coherence aligned with the body. The smooth narrative may be the CLS constructing clarity from incomplete data. The messy one may be someone whose bridge is opening for the first time.</p>
<div style={expandableRowStyle}><ExpandableSection title="Research Foundations" type="opendata"><p style={expandedProseStyle}>Main & Goldwyn (1998) — coherent narrative as a marker of earned security. Festinger (1957) — cognitive dissonance. Kahneman (2011) — coherence-seeking from available data.</p></ExpandableSection><ExpandableSection title="What TEG-Blue Adds" type="opendata"><p style={expandedProseStyle}>Three forms of coherence. Contested coherence as the clinical entry point. The smooth narrative as more likely to be coherence without the body.</p></ExpandableSection></div></section>

<section id="feeling-identity-fusion" aria-labelledby="heading-fif" style={{ marginBottom: 48 }}><h2 id="heading-fif" style={sectionHeadingStyle(P.C)}>Feeling-Identity Fusion</h2>
<p style={proseStyle}>When the bridge has never been built — or has closed — the CLS has no channel to separate {"\u201C"}what I feel{"\u201D"} from {"\u201C"}what I am.{"\u201D"}</p>
<p style={proseStyle}><strong style={{ color: TEXT.primary }}>Feeling = being.</strong> The person does not experience {"\u201C"}I feel scared.{"\u201D"} They are scared. <strong style={{ color: TEXT.primary }}>Feedback = identity.</strong> Criticism is not received as information. It is absorbed as who they are.</p>
<p style={proseStyle}>Every human being begins here. The infant does not feel fear and observe it. The infant IS the fear. The question is whether the bridge develops.</p>
<p style={proseStyle}>Two routes: <strong style={{ color: TEXT.primary }}>chronic suppression</strong> (bridge developed, then closed — repair requires unblocking) vs <strong style={{ color: TEXT.primary }}>developmental absence</strong> (bridge never built — repair requires building). Both produce the same condition. The distinction matters because unblocking and building are fundamentally different processes.</p>
<div style={expandableRowStyle}><ExpandableSection title="Research Foundations" type="opendata"><p style={expandedProseStyle}>Winnicott (1960) — true self and false self. Stern (1985) — development of the sense of self. Fonagy et al. (2002) — mentalization as developmental achievement.</p></ExpandableSection><ExpandableSection title="What TEG-Blue Adds" type="opendata"><p style={expandedProseStyle}>Feeling-Identity Fusion through the CLS-ESS architecture. Two routes to the same condition — with different repair implications.</p></ExpandableSection></div></section>

<section id="awareness-and-completion" aria-labelledby="heading-acc" style={{ marginBottom: 48 }}><h2 id="heading-acc" style={sectionHeadingStyle(P.C)}>Awareness and Cycle Completion</h2>
<p style={proseStyle}>The full Emotional Somatic Cycle is now visible. The nervous system generates a signal (<Link href="/model/m1-emotions-as-signals" style={linkStyle}>M1</Link>). The nervous system shifts state (<Link href="/model/m2-nervous-system-states" style={linkStyle}>M2</Link>). The body either completes or stays open (<Link href="/model/m3-regulation-capacities" style={linkStyle}>M3</Link>). The biological architecture determines whether the person can perceive any of it (M4).</p>
<p style={proseStyle}>RE — a CLS capacity on the external observation substrate — reads signals in others. This is why RE survives every chronic state. ER — an ESS capacity on the interoceptive substrate — feels what those signals carry. This is why ER degrades first. SEA — the bridge — determines whether the CLS has access to its own ESS{"'"}s state.</p>
<p style={proseStyle}><strong style={{ color: TEXT.primary }}>The loop.</strong> The chain feeds itself in both directions. Degradation: the CLS operating without the body further depletes the substrate, which reduces access, which strengthens coherence without the body, which deepens the override. Restoration: the sequence rebuilds the substrate, which opens access, which gives the CLS more data, which makes the next restoration more likely.</p>
<p style={proseStyle}>The Emotional Somatic Cycle runs in every nervous system. The biological architecture determines whether the person knows it.</p>
<div style={expandableRowStyle}><ExpandableSection title="Research Foundations" type="opendata"><p style={expandedProseStyle}>The loop draws on McEwen (2000), van der Kolk (2014), and Schore (2003).</p></ExpandableSection><ExpandableSection title="What TEG-Blue Adds" type="opendata"><p style={expandedProseStyle}>The loop as bidirectional: degradation amplifies degradation, restoration amplifies restoration. The architecture amplifies whichever direction it is running.</p></ExpandableSection></div></section>


<ConnectionsMap color={P.D} connections={[
{ id: "M1: Emotions as Signals", href: "/model/m1-emotions-as-signals", description: "Describes the signals the ESS generates — what RE reads from the outside, what ER feels in the body, what SEA carries to the CLS." },
{ id: "M2: Nervous System States", href: "/model/m2-nervous-system-states", description: "Describes the state the signal produces — M4 explains the mechanism behind State Determines Capacity: the three channels and the interoceptive substrate are what states actually determine." },
{ id: "M3: Regulation Capacities", href: "/model/m3-regulation-capacities", description: "Describes whether activation resolves — M4 explains whether the person can perceive the branching point, distinguish a substitute from genuine restoration, and detect the override." },
{ id: "F2: Developmental Calibration", href: "/framework/f2-awareness-calibration", description: "Explains how the awareness capacities develop through the relational environment — what builds the bridge, and what happens when the conditions are absent." },
{ id: "F3: Adult Cognition and False Coherence", href: "/framework/f3-false-coherence", description: "Explains how coherence without the body maintains itself — the cognitive maintenance layer of the regulation thread." },
]} />

<NavSection color={P.D} items={[
{ label: "Understand the signals the ESS generates — the first stage of the cycle", href: "/model/m1-emotions-as-signals", linkText: "M1: Emotions as Signals \u2192" },
{ label: "See how the state reorganizes perception before cognition arrives", href: "/model/m2-nervous-system-states", linkText: "M2: Nervous System States \u2192" },
{ label: "Understand whether the activation sequence completes — and what accumulates", href: "/model/m3-regulation-capacities", linkText: "M3: Regulation Capacities \u2192" },
{ label: "Explore how the awareness capacities develop through early relational experience", href: "/framework/f2-awareness-calibration", linkText: "F2: Developmental Calibration \u2192" },
{ label: "Explore the interactive tools", href: "https://teg-blue.com/emotional-tools", linkText: "teg-blue.com \u2192", external: true },
]} />

</article></PageLayout><SiteFooter />
<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "ScholarlyArticle", "@id": "https://teg-blue.org/model/m4-awareness-capacities#article", headline: "Awareness Capacities: The Calibration", description: "What determines whether the person can perceive the Emotional Somatic Cycle while it is running. Model M4.", author: { "@type": "Person", name: "Anna Paretas-Artacho", url: "https://teg-blue.org/about" }, publisher: { "@type": "Organization", name: "TEG-Blue Research", url: "https://teg-blue.org" }, datePublished: "2026-03-21", dateModified: "2026-04-06", inLanguage: "en", license: "https://creativecommons.org/licenses/by-nc-sa/4.0/", isPartOf: { "@type": "CreativeWork", name: "TEG-Blue Models & Frameworks", url: "https://teg-blue.org/models" }, mainEntityOfPage: { "@type": "WebPage", "@id": "https://teg-blue.org/model/m4-awareness-capacities" }, about: [{ "@type": "Thing", name: "Awareness Capacities" }, { "@type": "Thing", name: "Interoceptive Self-Awareness" }], keywords: ["awareness capacities","interoceptive self-awareness","affective resonance","interpersonal affect perception"] }) }} />
<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(generateBreadcrumbJsonLd([{ name: "Home", url: "/" }, { name: "The Emotional Somatic System", url: "/models" }, { name: "M4: Awareness Capacities", url: "/model/m4-awareness-capacities" }])) }} />
<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(generateFAQJsonLd([{ question: "What are the three awareness capacities?", answer: "RE reads emotional states in others (CLS capacity, external substrate). ER feels what others feel in one's own body (ESS capacity, interoceptive substrate). SEA perceives one's own physiological state (bridge between systems, interoceptive substrate)." }, { question: "Why does RE sharpen while ER degrades?", answer: "They operate through different substrates. RE uses the external observation substrate, unaffected by chronic activation. ER uses the interoceptive substrate, which degrades under sustained cortisol. When ER and SEA lose access, all cognitive resources concentrate on RE." }, { question: "What is the paradox of awareness?", answer: "The bridge needed to see the pattern is the bridge the pattern closes. SEA is built on the interoceptive substrate. Chronic activation degrades that substrate. The capacity needed to observe chronic activation is the capacity it takes offline." }])) }} />
<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(generateSpeakableJsonLd({ name: "Awareness Capacities (M4)", url: "https://teg-blue.org/model/m4-awareness-capacities", cssSelectors: ["article > section:first-of-type p", "article h2", "article h2 + p"] })) }} />
</div>); }
