"use client";

import { TEXT, FONT, BORDER, SPECTRUM, hexToRgba } from "@/src/styles/tokens";

const prose = {
  fontSize: 14,
  color: TEXT.secondary,
  lineHeight: 1.8,
  marginBottom: 16,
};

const emphasis = {
  color: TEXT.primary,
  fontWeight: 600,
};

const standaloneLine = {
  fontSize: 15,
  fontWeight: 600,
  color: TEXT.primary,
  lineHeight: 1.6,
  margin: "20px 0",
};

// ─── WHAT IT IS ─────────────────────────────────────────────

export const whatItIs = (
  <>
    <p style={prose}>
      Concept 1 establishes that emotions are the signalling language through
      which the nervous system delivers its evaluation. Concept 2 identifies the
      question that evaluation is answering.
    </p>
    <p style={standaloneLine}>
      "Is there enough safety to engage, or is protection needed?"
    </p>
    <p style={prose}>
      This is the fundamental organising question that the nervous system
      continuously evaluates. This evaluation is automatic, continuous, and below
      conscious awareness. Stephen Porges named this process "neuroception" — the
      nervous system's below-conscious evaluation of safety and threat. Every
      emotional signal the body generates is, at root, an answer to this
      question. It determines whether learning is possible or defence is
      required, whether trust is available or verification is needed, whether
      vulnerability is safe or control is necessary.
    </p>
    <p style={prose}>
      The extraordinary range of human emotional experience — from empathy to
      defensiveness, from curiosity to withdrawal, from openness to shutdown — is
      generated by variations on this single evaluation.{" "}
      <strong style={emphasis}>
        Every emotion the body signals is a variation on: safe enough, or not
        yet.
      </strong>
    </p>
    <p style={prose}>
      This does not mean the evaluation is simple. The body's assessment
      considers hundreds of variables simultaneously — facial expressions, tone
      of voice, body language, past experience, current physiological state,
      context. The output is rich, nuanced, and specific. But the question
      generating all that output is one question.
    </p>
    <p style={prose}>
      <strong style={emphasis}>
        The evaluation assesses <em>experienced</em> safety — not objective
        danger.
      </strong>{" "}
      Two people in the same room can have nervous systems reporting entirely
      different safety levels. Neither is wrong. Each system is evaluating based
      on its own history — what it learned to read as safe, what it learned to
      read as threat. This distinction — experienced safety, not objective danger
      — explains most of what gets labelled "overreaction." The person is not
      overreacting. Their nervous system is responding to what it perceives, and
      what it perceives is shaped by what it learned.
    </p>
  </>
);

// ─── WHERE IT COMES FROM ────────────────────────────────────

export const whereItComesFrom = (
  <>
    <p style={prose}>
      Porges (2011) — neuroception evaluates safety/threat continuously. Bowlby
      (1969) — the attachment system scans for safety/threat. Maslow (1943) —
      safety as foundational need. Siegel (2012) — safety enables integration
      and development.
    </p>
  </>
);

// ─── WHAT TEG-BLUE ADDS ────────────────────────────────────

export const whatTegBlueAdds = (
  <>
    <p style={prose}>
      Distilling the entire evaluation-and-signalling process to one clear
      question that explains why different responses occur. TEG-Blue does not
      just say "safety matters." It positions the safety question as the single
      question that the nervous system's signalling language is always answering
      — the question that generates all emotional diversity, from empathy to
      defensiveness, from curiosity to withdrawal. The question is universal:
      every nervous system runs it, every emotion answers it, every human
      response can be understood through it.
    </p>
    <p style={prose}>
      The distinction between experienced safety and objective danger is made
      maximally clear. This single distinction explains most interpersonal
      confusion: why someone reacts to feedback as though it were an attack, why
      someone shuts down in a situation that looks perfectly safe from outside,
      why someone cannot learn in an environment that appears supportive. The
      evaluation does not assess what is happening. It assesses what the nervous
      system <em>reads</em> as happening — and the reading is shaped by
      everything the system has learned.
    </p>
  </>
);
