"use client";

import { TEXT, FONT, BORDER, SPECTRUM, hexToRgba } from "@/src/styles/tokens";

const prose = {
  fontSize: 14,
  color: TEXT.secondary,
  lineHeight: 1.8,
  marginBottom: 16,
};

const emphasis = {
  color: TEXT.primary,
  fontWeight: 600,
};

const standaloneLine = {
  fontSize: 15,
  fontWeight: 600,
  color: TEXT.primary,
  lineHeight: 1.6,
  margin: "20px 0",
};

const numberedItem = {
  fontSize: 14,
  color: TEXT.secondary,
  lineHeight: 1.8,
  marginBottom: 10,
  paddingLeft: 8,
};

// ─── WHAT IT IS ─────────────────────────────────────────────

export const whatItIs = (
  <>
    <p style={prose}>
      <strong style={emphasis}>False coherence</strong> occurs when cognition
      constructs a stable internal narrative that preserves identity consistency,
      suppresses emotional contradiction, and reduces nervous system stress —
      even when that narrative no longer reflects lived reality.
    </p>
    <p style={prose}>
      False coherence is experienced as certainty, moral clarity, being "right,"
      and internal relief. This relief is{" "}
      <strong style={emphasis}>physiological</strong>, not epistemic — the body
      calms because the story holds together, not because the story is accurate.
    </p>
    <p style={standaloneLine}>
      Beliefs feel true because they restore nervous system stability, not
      because they match reality.
    </p>
    <p style={prose}>
      <strong style={emphasis}>False coherence is not deception.</strong> The
      person is not lying. They genuinely believe their constructed narrative
      because believing it reduces threat. It is regulatory success at the cost
      of emotional truth. The system is <em>succeeding</em> at regulation. The
      cost is truth, not function.
    </p>
    <p style={prose}>
      This is what makes it so hard to challenge. You are not confronting a lie.
      You are confronting a regulatory strategy that is actively keeping the
      person's nervous system stable. Challenging it directly increases threat —
      which triggers the system to produce <em>more</em> false coherence, not
      less.
    </p>
    <p style={{ ...prose, fontWeight: 500, color: TEXT.primary }}>
      The mechanism operates through a self-reinforcing loop:
    </p>
    <p style={numberedItem}>
      <strong style={emphasis}>1.</strong> State shifts under stress — the
      nervous system moves toward protection
    </p>
    <p style={numberedItem}>
      <strong style={emphasis}>2.</strong> Attention narrows — toward threat
      cues, away from contradictory data
    </p>
    <p style={numberedItem}>
      <strong style={emphasis}>3.</strong> Cognition generates a stabilising
      narrative — replacing the emotional signal with an invented explanation
    </p>
    <p style={numberedItem}>
      <strong style={emphasis}>4.</strong> The narrative holds — identity feels
      coherent, the body calms
    </p>
    <p style={numberedItem}>
      <strong style={emphasis}>5.</strong> Relief reinforces the pattern —
      cognition learns "this works"
    </p>
    <p style={numberedItem}>
      <strong style={emphasis}>6.</strong> The loop hardens — the replacement
      narrative becomes more automatic, more invisible, more "who I am"
    </p>
    <p style={prose}>
      Each cycle makes the replacement more automatic and the original signal
      harder to detect. The person is not getting worse — the system is getting
      better at the strategy that works for regulation but not for truth. Each
      cycle also deepens the disconnect from the biological return (Concept 5).
      Every time cognition successfully replaces an emotional signal, the body's
      own regulatory system gets less practice.
    </p>
    <p style={prose}>
      <strong style={emphasis}>
        This explains why insight alone does not break the pattern.
      </strong>{" "}
      Understanding the pattern is itself a cognitive event — and the cognitive
      system is the one running the replacement. "I know I do this" is itself a
      narrative generated by the same system that generated the false coherence.
      The loop can incorporate insight without breaking. This is what people
      experience as "I understand everything about my pattern and nothing
      changes." The understanding is cognitive. The regulation is cognitive. More
      cognition does not interrupt cognitive regulation — it enhances it.
    </p>
    <p style={prose}>
      <strong style={emphasis}>
        The most articulate, psychologically literate people can be the most
        stuck.
      </strong>{" "}
      Their cognitive system is so good at generating replacement narratives that
      the replacements include narratives <em>about</em> having emotions. "I
      felt really triggered and then I sat with it and processed it" — narrated
      by a cognitive system that replaced the actual feeling with a story about
      having the feeling. The cognitive regulation is so sophisticated that it
      includes regulation that looks like emotional processing but is actually
      more cognitive replacement.
    </p>
    <p style={prose}>
      <strong style={emphasis}>
        "Common sense" as pattern imprint:
      </strong>{" "}
      What feels like obvious truth may be a coherence strategy calibrated in
      childhood. "That's just how the world works" is often false coherence from
      childhood conditions that cognition preserved and presents as universal
      wisdom.
    </p>
  </>
);

// ─── WHERE IT COMES FROM ────────────────────────────────────

export const whereItComesFrom = (
  <>
    <p style={prose}>
      Festinger (1957) — cognitive dissonance and resolution. Haidt (2001) —
      moral reasoning as post-hoc justification. Kahneman (2011) — System
      1/System 2, coherence-seeking. Freud — defence mechanisms become automatic
      and rigid. Narrative psychology — coherent life stories as regulatory
      function. Family systems — how families maintain "accepted reality."
      Cognitive therapy — how beliefs become rigid. Porges (2011) — nervous
      system state gates cognition. Siegel (2012) — state-dependent processing
      capacity.
    </p>
  </>
);

// ─── WHAT TEG-BLUE ADDS ────────────────────────────────────

export const whatTegBlueAdds = (
  <>
    <p style={prose}>
      The term "false coherence" — capturing what no existing term does. It is
      not denial (which implies awareness of what is being denied). It is not
      rationalisation (which implies a specific tactic). It is not defence
      mechanism (which implies a list). False coherence is the <em>outcome</em>:
      a narrative that works for stability but not for truth. Complete, coherent,
      felt as real — and wrong.
    </p>
    <p style={prose}>
      The formulation "regulatory success at the cost of emotional truth"
      captures the non-pathologising stance and connects directly to the
      regulation thread. False coherence <em>is</em> the regulation strategy
      that develops when the biological return (Concept 5) was never learned. The
      person does not experience themselves as unable to regulate. They
      experience themselves as regulated — because cognition is doing the
      regulating. The deficit is invisible because the substitute is working. You
      are not confronting a person who cannot regulate. You are confronting a
      person who <em>is</em> regulating — through a system that costs truth
      rather than restores it.
    </p>
    <p style={prose}>
      The clinical implication flows directly: if false coherence is regulatory,
      then challenging it directly increases threat.{" "}
      <strong style={emphasis}>Safety must precede truth.</strong> This matches
      Concept 4 — "restore safety first, then expect capacity." You cannot
      out-think a regulatory response. You can only create conditions safe enough
      for the system to let truth in.
    </p>
  </>
);
