"use client";

import Link from "next/link";
import { TEXT, FONT, BORDER, SPECTRUM, hexToRgba } from "@/src/styles/tokens";

const prose = { fontSize: 14, color: TEXT.secondary, lineHeight: 1.8, marginBottom: 16 };
const emphasis = { color: TEXT.primary, fontWeight: 600 };
const standaloneLine = { fontSize: 15, fontWeight: 600, fontStyle: "italic", color: TEXT.primary, lineHeight: 1.6, margin: "24px 0" };
const separator = { width: 40, height: 1, background: BORDER.default, margin: "28px 0", border: "none" };
const conceptLink = { color: SPECTRUM.azure, textDecoration: "none", fontWeight: 500, fontSize: 13 };

export const body = (
  <>
    <p style={prose}>
      We all have a story about who we are. "I'm the responsible one." "I'm the
      strong one." "I'm the one who keeps it together." Sometimes the story
      matches reality. But sometimes it is doing a different job — it is not
      describing what's happening inside us. It is regulating us.
    </p>
    <p style={prose}>
      The story feels true not because it matches what is actually happening. It
      feels true because believing it calms us down.
    </p>

    <hr style={separator} />

    <p style={prose}>
      False coherence occurs when the mind constructs a stable narrative that
      preserves identity, suppresses emotional contradiction, and reduces
      nervous system stress — even when that narrative no longer reflects what
      we actually feel.{" "}
      <Link href="/concepts/the-safety-orientation-question" style={conceptLink}>
        {"\u2192"} The Safety Orientation Question
      </Link>
    </p>
    <p style={prose}>
      <strong style={emphasis}>
        Beliefs feel true because they restore nervous system stability, not
        because they match reality.
      </strong>
    </p>
    <p style={prose}>
      This means the feeling of being right — the feeling of certainty, of
      clarity — is not a reliable indicator that we are actually right. It might
      just mean the story is working.
    </p>

    <hr style={separator} />

    <p style={prose}>
      False coherence builds when the biological return was never learned.{" "}
      <Link href="/concepts/regulation-the-return-mechanism" style={conceptLink}>
        {"\u2192"} Regulation — The Return Mechanism
      </Link>{" "}
      The body activates under threat and the return doesn't happen. So
      cognition takes over the regulatory function — generating narratives that
      calm what the body cannot settle on its own.{" "}
      <Link href="/concepts/awareness-teaches-awareness" style={conceptLink}>
        {"\u2192"} Awareness Teaches Awareness
      </Link>
    </p>
    <p style={prose}>
      "The world is dangerous" — and from chronic Protection, every piece of
      evidence confirms it.{" "}
      <Link href="/concepts/the-inner-compass" style={conceptLink}>
        {"\u2192"} The Inner Compass
      </Link>{" "}
      "I'm just being strategic" — and from chronic Control, every override
      feels like competence. "They deserved it" — and from chronic Domination,
      every escalation feels justified.
    </p>
    <p style={prose}>
      Each chronic mode has its own false coherence. Each narrative makes the
      stuck position feel like truth. And each narrative does the job the
      biological return was supposed to do — which is why the mode never
      releases.{" "}
      <Link href="/concepts/state-determines-capacity" style={conceptLink}>
        {"\u2192"} State Determines Capacity
      </Link>
    </p>
    <p style={prose}>
      The cost is truth. The person is regulated by a story, not by felt
      experience.{" "}
      <Link href="/concepts/self-emotional-awareness" style={conceptLink}>
        {"\u2192"} Self-Emotional Awareness
      </Link>
    </p>

    <hr style={separator} />

    <p style={prose}>
      The most frustrating thing about false coherence: understanding doesn't
      break it. "I know I do this" is itself a narrative generated by the same
      cognitive system running the replacement. The loop can incorporate insight
      without breaking. The most articulate, psychologically literate people can
      be the most stuck — their cognitive system is so sophisticated that the
      replacement narratives include narratives about having emotions.
    </p>
    <p style={prose}>
      More cognition does not interrupt cognitive regulation. It enhances it.
    </p>

    <hr style={separator} />

    <p style={prose}>
      If false coherence is regulatory, challenging it directly increases
      threat — and increased threat produces more false coherence, not less.
      What changes it is what changes everything the compass describes:
      experienced safety.{" "}
      <Link href="/concepts/the-safety-orientation-question" style={conceptLink}>
        {"\u2192"} The Safety Orientation Question
      </Link>
    </p>
    <p style={prose}>
      Not being told they're safe. Relationships where the nervous system
      settles enough that the narrative can loosen without the whole system
      collapsing. Safety must precede truth.
    </p>
    <p style={prose}>
      This is the biological return, learned late.{" "}
      <Link href="/concepts/regulation-the-return-mechanism" style={conceptLink}>
        {"\u2192"} Regulation — The Return Mechanism
      </Link>{" "}
      The body learns that it can come back from discomfort without the
      narrative stepping in. Each time that happens, the false coherence
      loosens — not because it was argued away, but because it became less
      necessary.
    </p>

    <hr style={separator} />

    <p style={prose}>
      False coherence also operates at the collective level. "That's just how
      the world works." "Feelings are weakness." These often feel like common
      sense — but many are coherence strategies calibrated in childhood and
      passed down as truth.{" "}
      <Link href="/concepts/awareness-teaches-awareness" style={conceptLink}>
        {"\u2192"} Awareness Teaches Awareness
      </Link>{" "}
      <Link href="/concepts/tolerance-thresholds" style={conceptLink}>
        {"\u2192"} Tolerance Thresholds
      </Link>
    </p>
    <p style={prose}>
      The question is always the same: does this belief match what is actually
      happening — or does it regulate something that was never resolved?
    </p>

    <hr style={separator} />

    <p style={standaloneLine}>
      <em>
        You cannot out-think a regulatory response. You can only create
        conditions safe enough for the system to let truth in.
      </em>
    </p>
  </>
);
